src/asm.rs
src/interrupt/mod.rs
src/interrupt/mouse.rs

Old asm! syntax is no longer supported.

[Change]Use new asm! syntax

---

.github/workflows/rust.yml

Use Github Actions

---

asm/head.asm
src/asm.rs
src/gdt.rs
src/lib.rs

Initialize GDT in kernel, not head file

---

asm/head.asm
bootx64/src/main.rs

[Change]Disable interruptions during uefi booting

---

src/asm.rs

[Add]asm! options

---

src/asm.rs
src/descriptor_table.rs

[Refactoring]Rename to lidt

---

src/asm.rs
src/descriptor_table.rs

[Refactoring]Define limit as u16

---

src/graphics/screen.rs
src/interrupt/mouse.rs
src/lib.rs

Applying immutable programming to them is too difficult.

[Refactoring]Mutate Cursor and Device

---

src/graphics/mod.rs
src/graphics/screen.rs
src/interrupt/mouse.rs
src/lib.rs

The information of vram will be passed from uefi booting. To refer this
info, make this a singleton.

[Refactoring]Make vram a singleton

---

src/interrupt/mouse.rs

To limit the possible phases.
Fixes: #29

[Refactoring]Define DevicePhase enum

---

.travis.yml

Can't solve the problem of rust-src not installed correctly.

[Add].travis.yml

---

bootx64/src/exit.rs
os.ld

To save the size of memory needed for the kernel.

[Change]Store the address of os_main

---

bootx64/src/exit.rs
bootx64/src/fs.rs
bootx64/src/gop.rs
bootx64/src/init.rs
bootx64/src/main.rs
bootx64/src/memory.rs
src/descriptor_table.rs
src/gdt.rs
src/graphics/screen.rs
src/interrupt/mod.rs
src/interrupt/mouse.rs
src/lib.rs

Caller first

---

bootx64/src/memory.rs

Refactor memory code

---

Cargo.toml
bootx64/src/exit.rs
bootx64/src/gop.rs
bootx64/src/main.rs
common_items/Cargo.toml
common_items/src/lib.rs
src/graphics/mod.rs
src/lib.rs

Define addresses in `common_items` crate
Fixes: #60

Create common_items crate

---

bootx64/src/mem/paging.rs

[Fix]Not checking page num

---

bootx64/Cargo.toml
bootx64/src/init.rs
common_items/Cargo.toml

[Fix]Fail to build

---

src/interrupt/mouse.rs
src/lib.rs

Refactor put data

---

bootx64/src/exit.rs
bootx64/src/mem/paging.rs
common_items/Cargo.toml
common_items/src/lib.rs
src/graphics/mod.rs

[Change]Don't save info on memory

---

common_items/src/lib.rs
src/graphics/mod.rs
src/graphics/screen.rs

[Change]From u16 to usize

---

bootx64/src/mem/paging.rs
common_items/src/constant.rs

[Fix]Forgot to map PML4

---

bootx64/src/mem/paging.rs
common_items/src/constant.rs

Enable recursive paging

---

Makefile

[Fix]Not detecting changes in subcrates

---

Cargo.toml
Makefile
bootx64/Cargo.toml
bootx64/src/main.rs
common_items/src/debug.rs
common_items/src/lib.rs
debug/Cargo.toml
src/lib.rs

[Change]debug codes are included in common_items

---

kernel/src/interrupt.rs

[Refactoring]`init_pic`

---

Makefile

[Refactoring]Remove unused variable

---

bootx64/src/exit.rs
bootx64/src/main.rs
bootx64/src/mem/paging.rs

[Change]Init paging before exiting boot services

---

kernel/memlib/lib.c

[Refactoring]Rewrite `memmove`

---

bootx64/src/exit.rs
bootx64/src/fs/kernel.rs
bootx64/src/main.rs
bootx64/src/mem.rs
bootx64/src/mem/paging.rs
common/src/boot.rs
common/src/constant.rs
common/src/mem.rs
common/src/mem/reserved.rs
common/src/size.rs

Define reserved mem

---

bootx64/src/mem/paging.rs

[Change]Use functions of `x86_64`

---

kernel/src/graphics.rs
kernel/src/graphics/screen.rs
kernel/src/interrupt/handler.rs
kernel/src/interrupt/mouse.rs
kernel/src/lib.rs
kernel/src/panic.rs

To get information about the panic.

Implement Red Screen

---

bootx64/src/main.rs
common/src/lib.rs

[Refactoring]Remove unnecessary `extern crate`

---

kernel/Cargo.toml
kernel/src/gdt.rs
kernel/src/graphics.rs
kernel/src/idt.rs
kernel/src/interrupt.rs
kernel/src/interrupt/mouse.rs

[Refactoring]Remove `lazy_static`

---

common/src/constant.rs
kernel/src/mem/allocator/virt.rs

Create virtual address allocator

---

kernel/src/lib.rs
kernel/src/mem/paging/mod.rs

Mark all pages which are not kernel one unused

---

kernel/src/panic.rs

Remove Redscreen

---

bors.toml

Remove branch after merging

---

kernel/src/idt.rs
kernel/src/interrupt.rs

Add temporary exception handlers

---

kernel/src/device/pci/xhci/mod.rs
kernel/src/device/pci/xhci/transfer_ring/mod.rs
kernel/src/interrupt.rs
kernel/src/lib.rs

Add xhci task

---

bootx64/Cargo.toml
bootx64/src/fs/kernel/mod.rs
bootx64/src/fs/kernel/size.rs
common/Cargo.toml
common/src/constant.rs
common/src/mem/reserved.rs
common/src/vram.rs
kernel/Cargo.toml
kernel/src/device/pci/config/extended_capability/msi_x.rs
kernel/src/device/pci/xhci/event_ring/mod.rs
kernel/src/device/pci/xhci/mod.rs
kernel/src/device/pci/xhci/register/hc_operational_registers.rs
kernel/src/mem/accessor/mod.rs
kernel/src/mem/accessor/single_object.rs
kernel/src/mem/accessor/slice.rs
kernel/src/mem/allocator/virt.rs

Update the version of `os_units` crate

---

kernel/src/mem/allocator/phys.rs

Implement buddy allocator

---

kernel/src/device/pci/xhci/mod.rs

Fix an invalid ERSTSZ

---

Makefile

Remove unused variables in Makefile

---

kernel/src/panic.rs

Disable interruptions in the panic handler

---

kernel/src/graphics/mod.rs

- Remove a line
- Define `Bgr`
- Use `Bgr` type
Fixes: #184
bors r+

Remove inappropriate `offset`

---

Makefile
trace.event

Enable trace for xHCI

---

kernel/src/device/pci/xhci/ring/command.rs
kernel/src/device/pci/xhci/ring/event/mod.rs
kernel/src/device/pci/xhci/ring/mod.rs
kernel/src/device/pci/xhci/ring/raw.rs
kernel/src/device/pci/xhci/ring/trb.rs

- Create `raw` module
- Move `Raw` into `raw` module
- Move the raw trb into `raw` module
bors r+

Create `raw` module

---

kernel/src/device/pci/xhci/ring/trb.rs

Remove unnecessary parentheses

---

kernel/src/device/pci/xhci/ring/raw.rs
kernel/src/device/pci/xhci/ring/trb.rs

Add command complete TRB

---

kernel/src/device/pci/xhci/ring/event/mod.rs

Fix the number of maximum size

---

kernel/Cargo.toml

- Remove an unnecessary comment
- Fix grammatical errors
bors r+

Fix comments

---

kernel/src/device/pci/xhci/mod.rs
kernel/src/device/pci/xhci/register/hc_capability_registers.rs
kernel/src/device/pci/xhci/register/hc_operational_registers.rs

- Define `NumberOfDeviceSlots`
- Fix
- Set the size of DCBAA with the number of slots
bors r+

Set the proper value to DCBAA size

---

bootx64/src/main.rs
bootx64/src/mem/free_page.rs
bootx64/src/mem/mod.rs
common/src/constant.rs
common/src/mem/reserved.rs

- Remove lines about the old implementation of memory manager
- Remove an unnecessary file
bors r+

Remove codes about the old implementation of memory manager

---

common/Cargo.toml
common/src/vram.rs
kernel/src/graphics/mod.rs

Save the resolution of the screen as a vector

---

kernel/src/device/mouse.rs

- Define `Buf`
- Define `speed_(x|y)_is_negative`
bors r+

Define `Buf` type for mouse device

---

kernel/src/multitask/executor.rs

`while` loop should contain only a line

---

kernel/src/device/keyboard.rs
kernel/src/graphics/screen/mod.rs

- Remove an unnecessary drawing
- Remove unnecessary lines
bors r+

Remove unnecessary drawing

---

kernel/src/device/keyboard.rs

- Remove blank lines
- Define `queue` method
- Public functions should come first
bors r+

Define `queue` function

---

kernel/src/device/keyboard.rs

Define `SIZE_OF_SCANCODE_QUEUE`

---

kernel/src/device/mouse.rs

- Define `handle_packet`
- Rename method names
- Define `parse_packets`
- Rename to `parse_packets`
bors r+

Move lines inside `while` block

---

kernel/src/device/mouse.rs

Define submethods

---

kernel/src/device/mouse.rs

- Define `DevicePhase::next`
- Use `if else`
bors r+

Use `if else`

---

kernel/src/device/mouse.rs

Define `queue` method

---

kernel/src/device/pci/xhci/mod.rs

Remove debug info

---

kernel/src/device/pci/xhci/mod.rs
kernel/src/device/pci/xhci/register/mod.rs

- Define `Registers`
- Add `registers` as a member
bors r+

Define `Registers` struct

---

kernel/src/device/pci/xhci/register/hc_operational_registers.rs

Return if HC is not halted

---

kernel/src/device/pci/xhci/mod.rs

To refer this struct from the event ring and the command ring.
bors r+

Split `Registers` member

---

kernel/src/device/pci/xhci/mod.rs
kernel/src/device/pci/xhci/register/hc_capability_registers.rs
kernel/src/device/pci/xhci/ring/event/mod.rs

- Add `registers` as a member
- Define `init_registers`
- Remove unnecessary `pub`s
- Abstractive method should come first
- Implement `From`
bors r+

Split the event ring

---

kernel/src/device/pci/xhci/ring/event/mod.rs

Use `cycle_bit` method

---

kernel/src/device/pci/xhci/ring/command.rs
kernel/src/device/pci/xhci/ring/raw.rs
kernel/src/device/pci/xhci/ring/trb.rs

- Define `Link` trb
- Define `Link::new`
- Append a link trb to the command ring
bors r+

Append a link trb to the command ring

---

kernel/src/device/pci/xhci/register/hc_capability_registers.rs

This method will be used to get port registers.
bors r+

Define `max_num_of_ports`

---

kernel/src/device/pci/xhci/mod.rs

Remove `generate` method

---

kernel/src/device/pci/xhci/dcbaa.rs
kernel/src/device/pci/xhci/mod.rs
kernel/src/device/pci/xhci/register/hc_capability_registers.rs

Split dcbaa

---

kernel/src/mem/allocator/page_box.rs

- Write 0 to all bytes of the allocated frames
- Define `write_all_bytes_with_zero` method
bors r+

`PageBox::new_slice`: Write all bytes with zero

---

kernel/src/device/pci/xhci/register/hc_capability.rs

Remove unnecessary lines

---

kernel/src/mem/accessor.rs

Remove a duplication

---

kernel/src/device/pci/xhci/dcbaa.rs

Refactor the code of DCBAA

---

kernel/src/device/pci/xhci/mod.rs

Reduce the number of lines

---

kernel/src/device/pci/xhci/mod.rs

Reset xHC after stopping it

---

kernel/src/device/pci/xhci/register/hc_operational.rs

Hide an unused getter

---

kernel/src/device/pci/xhci/register/doorbell.rs
kernel/src/device/pci/xhci/ring/command.rs
kernel/src/mem/accessor.rs

Implement volatile access for slice accessor

---

kernel/src/device/pci/xhci/mod.rs
kernel/src/device/pci/xhci/port.rs
kernel/src/device/pci/xhci/register/hc_operational.rs

Reset each port

---

kernel/src/device/pci/xhci/ring/raw.rs
kernel/src/device/pci/xhci/ring/trb.rs

Implement `PortStatusChange`

---

kernel/src/device/pci/xhci/mod.rs

Define `init` method

---

.github/workflows/test.yml
.gitignore
commitlint.config.js
package.json

- build: add rules to `.gitignore`
- chore: add configs of commitlint
- ci: add commitlint workflow
bors r+

Install `commitlint`

---

kernel/src/device/pci/xhci/mod.rs
kernel/src/device/pci/xhci/port.rs

refactor: define `enable_all_connected_ports`

---

kernel/src/device/pci/xhci/ring/command.rs

refactor: reduce the number of lines

---

kernel/src/interrupt.rs
kernel/src/lib.rs
kernel/src/multitask/executor.rs
kernel/src/multitask/task.rs

- refactor: refactor executor to add tasks
- feat: enable to add tasks
This enables to create USB device tasks.
bors r+

Enable to add tasks

---

kernel/src/device/pci/xhci/mod.rs
kernel/src/device/pci/xhci/ring/event/mod.rs

refactor: create an event ring task

---

kernel/src/device/pci/xhci/mod.rs
kernel/src/device/pci/xhci/port.rs
kernel/src/lib.rs

- chore: spawn port tasks
- refactor: rename to `TaskSpawner`
bors r+

Spawn port tasks

---

kernel/src/device/pci/xhci/mod.rs
kernel/src/device/pci/xhci/ring/event/mod.rs

refactor: store a waker inside method

---

kernel/src/device/pci/xhci/command_runner.rs
kernel/src/device/pci/xhci/mod.rs
kernel/src/device/pci/xhci/ring/event/mod.rs
kernel/src/multitask/executor.rs

- fix: remove a waker when waking a runner
- refactor: rename functions
- refactor: remove a blank line
- fix: event ring sleeps forever if no trb is dequeueable
bors r+

fix cannot send multiple trbs

---

kernel/src/device/pci/xhci/command_runner.rs
kernel/src/device/pci/xhci/port.rs
kernel/src/device/pci/xhci/ring/command.rs
kernel/src/device/pci/xhci/ring/raw.rs
kernel/src/device/pci/xhci/ring/trb.rs

- chore: enable slot
- refactor: remove codes about `noop`
bors r+

Obtain slot ID

---

kernel/src/device/pci/xhci/context.rs
kernel/src/device/pci/xhci/dcbaa.rs
kernel/src/device/pci/xhci/port.rs
kernel/src/device/pci/xhci/ring/event/segment_table.rs
kernel/src/device/pci/xhci/ring/raw.rs
kernel/src/lib.rs
kernel/src/mem/allocator/page_box.rs

refactor: `PageBox::new(_slice)?` takes an initial value

---

Makefile
kernel/src/device/pci/ahci/mod.rs
kernel/src/device/pci/config/common.rs
kernel/src/device/pci/config/mod.rs
kernel/src/device/pci/mod.rs
kernel/src/lib.rs

chore: find an ahc

---

kernel/src/device/pci/ahci/ahc/mod.rs
kernel/src/device/pci/ahci/ahc/registers/generic.rs
kernel/src/device/pci/ahci/mod.rs

- chore: add the definition of GHC
- chore: derive Copy and Clone
- chore: indicate system software is ahci aware
bors r+

Indicate system software is ahci aware

---

kernel/src/device/pci/ahci/ahc/mod.rs
kernel/src/device/pci/ahci/ahc/registers/mod.rs
kernel/src/device/pci/ahci/ahc/registers/port.rs
kernel/src/device/pci/ahci/mod.rs

chore: make ports idle

---

kernel/src/device/pci/ahci/ahc.rs
kernel/src/device/pci/ahci/mod.rs
kernel/src/device/pci/ahci/port.rs

refactor: define `port` module

---

kernel/src/device/pci/xhci/mod.rs
kernel/src/device/pci/xhci/xhc.rs

refactor: define `xhc` module

---

kernel/src/device/pci/ahci/port/mod.rs
kernel/src/device/pci/ahci/port/received_fis.rs

chore: define `received_fis` module

---

kernel/src/device/pci/ahci/ahc.rs
kernel/src/device/pci/ahci/mod.rs
kernel/src/device/pci/ahci/port/command_list.rs
kernel/src/device/pci/ahci/port/mod.rs
kernel/src/device/pci/ahci/port/received_fis.rs
kernel/src/device/pci/ahci/registers/generic.rs
kernel/src/device/pci/ahci/registers/port.rs
kernel/src/mem/allocator/page_box.rs

- refactor: reorder methods
- chore: register addresses to ahci
- chore: assert that 64bit addressing is supported
bors r+

Register memory structures

---

kernel/src/device/pci/ahci/mod.rs
kernel/src/device/pci/ahci/port/mod.rs
kernel/src/device/pci/ahci/registers/port.rs

chore: clear error bits

---

kernel/src/device/pci/ahci/port/mod.rs
kernel/src/device/pci/ahci/registers/port.rs

- refactor: define helper methods
- chore: remove an unnecessary method
- refactor: remove common prefix
bors r+

Define helper methods

---

kernel/src/device/pci/ahci/ahc.rs
kernel/src/device/pci/ahci/mod.rs
kernel/src/device/pci/ahci/registers/generic.rs

chore: reset ahc

---

Makefile
kernel/src/device/pci/ahci/port/mod.rs

- chore: enable receiving fis
- chore: automatically create a fat img
bors r+

Enable receiving fis

---

kernel/src/device/pci/ahci/port/mod.rs
kernel/src/device/pci/ahci/registers/port.rs

chore: print port signature

---

kernel/src/device/pci/ahci/registers/port.rs

refactor: remove unnecessary variable declarations

---

kernel/src/device/pci/xhci/context.rs
kernel/src/device/pci/xhci/port.rs
kernel/src/device/pci/xhci/ring/transfer.rs

chore: initialize input default control endpoint 0 context

---

kernel/src/mem/allocator/page_box.rs

chore: implement `Display` for `PageBox`

---

kernel/src/mem/allocator/page_box.rs

chore: implement `Debug` for `PageBox`

---

kernel/src/device/pci/xhci/context.rs
kernel/src/device/pci/xhci/port.rs

- refactor: remove TODO comment
- chore: support 64-bit input control context
bors r+

Support 64bit input control context

---

kernel/src/device/pci/xhci/ring/trb.rs

- chore: define `SetupStage`
- chore: define `DataStage`
- chore: define `StatusStage`
bors r+

Define transfer TRBs

---

kernel/src/device/pci/xhci/ring/command.rs

refactor: reorder methods

---

kernel/src/device/pci/xhci/ring/transfer.rs

- chore: implement `TransferRing::enqueue`
- refactor: define `increment_enqueue_ptr`
- refactor: define `append_link_trb`
- refactor: define `move_enqueue_ptr_to_the_beginning`
bors r+

Implement enqueue for transfer ring

---

kernel/src/device/pci/xhci/ring/trb.rs

chore: define `TransferEvent`

---

kernel/src/device/pci/xhci/exchanger/command.rs

refactor: remove an unused variable

---

kernel/src/device/pci/xhci/exchanger/command.rs
kernel/src/device/pci/xhci/mod.rs

refactor: define `command::channel`

---

kernel/src/device/pci/xhci/mod.rs

refactor: shorten the name of variables

---

kernel/src/device/pci/xhci/mod.rs

refactor: remove an unnecessary `pub`

---

kernel/src/device/pci/xhci/exchanger/command.rs
kernel/src/device/pci/xhci/exchanger/mod.rs
kernel/src/device/pci/xhci/exchanger/receiver.rs
kernel/src/device/pci/xhci/mod.rs
kernel/src/device/pci/xhci/structures/ring/event/mod.rs

Receiver will be used by transfer exchanger.
bors r+

refactor: define `receiver` module

---

kernel/src/device/pci/xhci/structures/ring/command/mod.rs

refactor: define `enqueue_ptr_within_range`

---

kernel/src/device/pci/xhci/exchanger/command.rs
kernel/src/device/pci/xhci/exchanger/receiver.rs

- chore: `add_entry` returns `Result`
- chore: consume `Result`
bors r+

Return `Result` value

---

kernel/src/device/pci/xhci/structures/ring/command/trb.rs
kernel/src/device/pci/xhci/structures/ring/event/trb.rs
kernel/src/device/pci/xhci/structures/ring/mod.rs

refactor: introduce `add_trb` macro

---

kernel/src/device/pci/xhci/structures/ring/event/trb.rs

refactor: remove an unused import

---

kernel/src/device/pci/xhci/structures/ring/transfer/trb.rs

- chore: define `Trb`
- refactor: define `Control`
bors r+

Define the correct `Trb`

---

kernel/src/device/pci/xhci/structures/ring/transfer/trb/control.rs
kernel/src/device/pci/xhci/structures/ring/transfer/trb/mod.rs

- chore: define `Control::new_get_descriptor`
- chore: define `Trb::new_get_descriptor`
bors r+

Define `Trb::new_get_descriptor`

---

kernel/src/device/pci/xhci/structures/ring/transfer/trb/control.rs

refactor: remove an unused method

---

kernel/src/device/pci/xhci/structures/descriptor.rs
kernel/src/device/pci/xhci/structures/mod.rs

- chore: create `descriptor.rs`
- chore: define `descriptor::Device`
bors r+

Define `descriptor::Device`

---

kernel/src/device/pci/xhci/structures/ring/command/mod.rs

refactor: define `Initializer`

---

kernel/src/device/pci/xhci/structures/ring/command/mod.rs

- refactor: calculate the size of ring
- refactor: rename `SIZE_OF_RING` to `NUM_OF_TRBS`
bors r+

Calculate the number of TRBs

---

kernel/src/device/pci/xhci/structures/ring/event/mod.rs

Not to cross 64K boundary.
bors r+

fix: set the size of ring size to page size

---

kernel/src/device/pci/xhci/structures/ring/event/mod.rs
kernel/src/device/pci/xhci/structures/ring/event/segment_table.rs
kernel/src/device/pci/xhci/structures/ring/event/trb.rs

- chore: implement `TryFrom<[u32; 4]>` for `Trb`
- chore: define `event::Raw`
- chore: implement `IntoIterator` for `SegmentTable`
- chore: implement `SegmentTable::iter_mut`
- refactor: rewrite `Ring` with `Raw`
- refactor: rewrite `or_else` with `map_err`
bors r+

Define `event::Raw`

---

kernel/src/device/pci/xhci/structures/ring/event/mod.rs

refactor: remove an unused `Error`

---

kernel/src/device/pci/xhci/structures/ring/event/mod.rs

- refactor: define `SegTblInitializer`
- refactor: define `iter_tbl_entries_mut`
bors r+

Define segment table initializer

---

kernel/src/device/pci/xhci/structures/ring/mod.rs
kernel/src/device/pci/xhci/structures/ring/transfer/mod.rs
kernel/src/device/pci/xhci/structures/ring/transfer/trb/control.rs
kernel/src/device/pci/xhci/structures/ring/transfer/trb/mod.rs

Enqueue multiple TRBs on the transfer ring

---

kernel/src/device/pci/xhci/exchanger/command.rs
kernel/src/device/pci/xhci/port.rs
kernel/src/device/pci/xhci/structures/ring/command/mod.rs

fix: remove wrongly implemented full check

---

kernel/src/device/pci/xhci/structures/ring/transfer/mod.rs

fix: remove wrong implementation of checking whether the ring is full

---

kernel/src/device/pci/xhci/structures/ring/transfer/mod.rs

- refactor: remove an unused import
- refactor: remove an unused `Error` struct
bors r+

Remove unused lines

---

kernel/src/device/pci/xhci/structures/ring/transfer/trb/control.rs
kernel/src/device/pci/xhci/structures/ring/transfer/trb/mod.rs

Ring should set C bit.
bors r+

chore: remove `c` arguments

---

kernel/src/device/pci/xhci/structures/ring/transfer/trb/control.rs
kernel/src/device/pci/xhci/structures/ring/transfer/trb/mod.rs

- chore: get IOC bit from transfer TRB
- refactor: add a note
bors r+

Get IOC bit of the Control TRBs

---

kernel/src/device/pci/xhci/structures/ring/transfer/mod.rs

chore: implement `transfer::Ring::enqueue`

---

kernel/src/device/pci/xhci/exchanger/mod.rs
kernel/src/device/pci/xhci/exchanger/transfer.rs
kernel/src/device/pci/xhci/structures/descriptor.rs
kernel/src/device/pci/xhci/structures/ring/transfer/mod.rs
kernel/src/device/pci/xhci/structures/ring/transfer/trb/control.rs
kernel/src/device/pci/xhci/structures/ring/transfer/trb/mod.rs
kernel/src/lib.rs

- chore: add `transfer`
- chore: implement `Default` for `descriptor::Device`
- refactor: define transfer exchanger
bors r+

define transfer exchanger

---

kernel/src/mem/allocator/page_box.rs

fix: remove an unnecessary trait bound

---

kernel/src/device/pci/xhci/port.rs

refactor: define `Resetter`

---

kernel/src/device/pci/xhci/port.rs
kernel/src/device/pci/xhci/structures/context.rs

refactor: receive an argument by reference

---

kernel/src/device/pci/xhci/port.rs

- refactor: define `ContextInitializer`
- fix: passing arguments
bors r+

Define `ContextInitializer`

---

kernel/src/device/pci/xhci/port/mod.rs

refactor: define `Slot` type

---

kernel/src/device/pci/xhci/exchanger/transfer.rs

fix: forgot to await

---

kernel/src/panic.rs

refactor: define `print_banner`

---

kernel/src/panic.rs

refactor: define `print_panic_location`

---

kernel/src/device/pci/xhci/structures/ring/transfer/trb/control.rs
kernel/src/device/pci/xhci/structures/ring/transfer/trb/mod.rs

fix: implement `From` trait for `transfer::trb::TRB`

---

kernel/src/device/pci/xhci/exchanger/transfer.rs
kernel/src/device/pci/xhci/port/mod.rs
kernel/src/device/pci/xhci/structures/ring/transfer/trb/control.rs
kernel/src/device/pci/xhci/structures/ring/transfer/trb/mod.rs

- chore: add `Configuration` variant for `DescTy`
- chore: get the configuration descriptor
bors r+

Get the configuration descriptor

---

kernel/src/device/pci/xhci/structures/descriptor.rs

- chore: define fields of the Device descriptor
- chore: define getters
- fix: forgot to add `C` and `packed`
bors r+

Implement fields of `Device`

---

kernel/src/device/pci/xhci/exchanger/transfer.rs
kernel/src/device/pci/xhci/structures/descriptor.rs
kernel/src/device/pci/xhci/structures/ring/transfer/trb/control.rs

refactor: move `DescTy` into `descriptor` module

---

kernel/src/device/pci/xhci/port/mod.rs
kernel/src/device/pci/xhci/port/slot/mod.rs

- chore: add `slot` module
- refactor: move definitions into `slot` module
bors r+

Create `slot` module

---

kernel/src/device/pci/xhci/structures/descriptor.rs

refactor: remove an outdated comment

---

Makefile
kernel/src/device/pci/xhci/structures/descriptor.rs

- chore: define `Interface`
- chore: a variant takes a value
- fix: wrongly implemented fields
- chore: change a connected USB device to a keyboard
bors r+

Read the Interface descriptor

---

kernel/src/device/pci/xhci/port/context.rs
kernel/src/device/pci/xhci/structures/context.rs
kernel/src/device/pci/xhci/structures/ring/mod.rs

- refactor: rewrite with `bit_field`
- chore: define methods
bors r+

Define methods of `Endpoint`

---

kernel/src/device/pci/xhci/structures/context.rs

refactor: remove an unnecessary comment

---

kernel/src/device/pci/xhci/port/mod.rs
kernel/src/device/pci/xhci/port/slot/endpoint.rs
kernel/src/device/pci/xhci/port/slot/mod.rs

- chore: create `endpoint.rs`
- chore: wrap `context` with `Rc` and `RefCell`
- chore: define `Endpoint`
- chore: add `eps` as a member
- Revert "chore: add `eps` as a member"
- chore: define `Endpoint::init_context`
- refactor: define `endpoint::Collection`
bors r+

Define `endpoint::Collection`

---

kernel/src/device/pci/xhci/port/mod.rs
kernel/src/device/pci/xhci/port/slot/mod.rs

refactor: rename to `init`

---

kernel/src/device/pci/xhci/structures/ring/command/mod.rs

refactor: `Initializer` takes a mutable reference

---

kernel/src/device/pci/xhci/structures/ring/event/mod.rs

refactor: remove unnecessary wrappers

---

kernel/src/device/pci/xhci/structures/ring/event/mod.rs

refactor: `SegTblInitializer` takes a reference

---

kernel/src/device/pci/xhci/port/mod.rs

refactor: `num_of_ports` takes a reference

---

kernel/src/device/pci/xhci/structures/dcbaa.rs

refactor: method takes a reference

---

kernel/src/device/pci/xhci/mod.rs
kernel/src/device/pci/xhci/port/mod.rs
kernel/src/device/pci/xhci/port/slot/endpoint/mod.rs
kernel/src/device/pci/xhci/port/slot/mod.rs
kernel/src/lib.rs

chore: use `Futurelock` for `Send` and `Sync`

---

kernel/Cargo.toml
kernel/src/device/pci/ahci/ahc.rs
kernel/src/device/pci/ahci/mod.rs
kernel/src/device/pci/ahci/port/mod.rs
kernel/src/device/pci/xhci/exchanger/command.rs
kernel/src/device/pci/xhci/exchanger/receiver.rs
kernel/src/device/pci/xhci/exchanger/transfer.rs
kernel/src/device/pci/xhci/mod.rs
kernel/src/device/pci/xhci/port/mod.rs
kernel/src/device/pci/xhci/port/slot/endpoint/mod.rs
kernel/src/device/pci/xhci/port/slot/mod.rs
kernel/src/device/pci/xhci/structures/dcbaa.rs
kernel/src/device/pci/xhci/structures/ring/command/mod.rs
kernel/src/device/pci/xhci/structures/ring/event/mod.rs
kernel/src/device/pci/xhci/xhc.rs
kernel/src/lib.rs
kernel/src/multitask/executor.rs
kernel/src/multitask/task.rs

- chore: implement `Send` for `Task`
- refactor: use `static` task collection
bors r+

Define static `task::Collection`

---

kernel/src/device/pci/ahci/port/mod.rs
kernel/src/device/pci/config/type_spec/non_bridge.rs
kernel/src/device/pci/xhci/exchanger/transfer.rs
kernel/src/device/pci/xhci/port/mod.rs
kernel/src/device/pci/xhci/port/slot/endpoint/class_driver/keyboard.rs
kernel/src/device/pci/xhci/port/slot/endpoint/mod.rs
kernel/src/device/pci/xhci/structures/registers/usb_legacy_support_capability.rs
kernel/src/device/pci/xhci/structures/ring/event/mod.rs

chore: replace `info!` with `debug!`

---

kernel/src/fs/mod.rs
kernel/src/fs/ustar.rs
kernel/src/lib.rs

- chore: add `fs` module
- chore: define `ustar::Meta`
- chore: print the content of a tar file
bors r+

Read the content of initrd

---

kernel/src/device/pci/xhci/port/slot/endpoint/class_driver/keyboard.rs

chore: print typed letters

---

kernel/src/device/pci/xhci/port/mod.rs

refactor: remove `clippy::allow`

---

kernel/src/device/pci/ahci/port/mod.rs
kernel/src/device/pci/xhci/mod.rs
kernel/src/device/pci/xhci/port/mod.rs
kernel/src/lib.rs
kernel/src/multitask/mod.rs
kernel/src/multitask/task.rs

refactor: define a wrapper function

---

.github/workflows/test.yml

chore: fix typo

---

kernel/src/interrupt/pic.rs

fix: license comment

---

.clippy.toml
kernel/src/device/pci/xhci/exchanger/transfer.rs
kernel/src/device/pci/xhci/mod.rs
kernel/src/device/pci/xhci/port/mod.rs
kernel/src/device/pci/xhci/port/resetter.rs
kernel/src/device/pci/xhci/port/slot.rs
kernel/src/device/pci/xhci/structures/context.rs
kernel/src/device/pci/xhci/structures/dcbaa.rs
kernel/src/device/pci/xhci/structures/ring/command/mod.rs
kernel/src/device/pci/xhci/structures/ring/event/mod.rs
kernel/src/device/pci/xhci/xhc.rs

refactor: define a static `REGISTERS`

---

kernel/src/device/pci/xhci/mod.rs
kernel/src/device/pci/xhci/xhc.rs

refactor: remove `Xhc` struct

---

kernel/src/device/pci/xhci/mod.rs
kernel/src/device/pci/xhci/port/mod.rs
kernel/src/device/pci/xhci/port/slot.rs
kernel/src/device/pci/xhci/structures/dcbaa.rs

refactor: define a static `DCBAA`

---

kernel/src/device/pci/xhci/port/slot.rs

refactor: remove unnecessary letters

---

kernel/src/device/pci/xhci/port/slot.rs

refactor: define `generate_endpoint`

---

kernel/src/device/pci/xhci/port/slot.rs
kernel/src/device/pci/xhci/structures/descriptor.rs

refactor: define helper methods

---

kernel/src/mem/accessor.rs

refactor: introduce `bytes` variable

---

bootx64/Cargo.toml
common/Cargo.toml
kernel/Cargo.toml

chore(deps): update dependencies

---

kernel/Cargo.toml
kernel/src/acpi.rs
kernel/src/interrupt/apic/io.rs
kernel/src/interrupt/mod.rs
kernel/src/interrupt/timer.rs
kernel/src/lib.rs

- feat: implement ACPI PM timer
- refactor: create `acpi` module
- style: add underscores to divide a numeric literal
- refactor: remove duplicate module name
- feat: implement timer interruption
- refactor: reorder lines
- refactor: remove an unnecessary `pub`
bors r+

Implement timer

---

kernel/src/gdt.rs
kernel/src/lib.rs
kernel/src/tss.rs

chore: implement TSS

---

kernel/src/mem/allocator/page_box.rs

chore: implement `virt_addr` for `PageBox`

---

Makefile
kernel/src/device/pci/xhci/port/class_driver/mouse.rs
kernel/src/device/pci/xhci/port/endpoint.rs
kernel/src/device/pci/xhci/port/mod.rs
kernel/src/device/pci/xhci/port/slot.rs
kernel/src/device/pci/xhci/structures/descriptor.rs

- chore: add `usb-mouse` as a device
- chore: add `mouse` module
- feat: read packets from USB mouse
- refactor: use `find_map`
- chore: pretty print
bors r+

Read packets from USB mouse

---

kernel/src/device/pci/xhci/mod.rs

chore: exit from xHCI task if xHC is not found

---

kernel/src/interrupt/timer.rs

Faster than the trait object.
bors r+

refactor: use `enum` for `Reader`

---

kernel/src/graphics/screen/cursor.rs
kernel/src/graphics/screen/desktop.rs
kernel/src/graphics/screen/layer.rs

refactor: expose `add`, `edit`, and `slide` functions

---

kernel/src/acpi.rs
kernel/src/device/pci/ahci/mod.rs
kernel/src/device/pci/ahci/registers/generic.rs
kernel/src/device/pci/ahci/registers/mod.rs
kernel/src/device/pci/ahci/registers/port.rs
kernel/src/device/pci/config/mod.rs
kernel/src/device/pci/xhci/mod.rs
kernel/src/device/pci/xhci/structures/descriptor.rs
kernel/src/device/pci/xhci/structures/registers/capability.rs
kernel/src/device/pci/xhci/structures/registers/mod.rs
kernel/src/device/pci/xhci/structures/registers/operational.rs
kernel/src/device/pci/xhci/structures/registers/runtime.rs
kernel/src/device/pci/xhci/structures/registers/usb_legacy_support_capability.rs
kernel/src/interrupt/apic/io.rs
kernel/src/interrupt/apic/local.rs
kernel/src/interrupt/timer.rs
kernel/src/mem/accessor.rs
kernel/src/mem/allocator/page_box.rs
kernel/src/syscall.rs

style: apply the term highlight of Vim

---

kernel/src/fs/ustar.rs
kernel/src/lib.rs

- chore: define `UStar` struct
- refactor: rewrite with `UStar::list`
- chore: mark `UStar::new` as unsafe
- refactor: define `iter` method
- chore: define `Meta::name` method
- refactor: rename to `Ustar`
- chore: define `UStar::content`
bors r+

chore: open a file in initrd

---

Makefile
syscalls/src/lib.rs

fix: not all cargo projects were checked

---

kernel/src/process/mod.rs
kernel/src/process/stack_frame.rs

- chore: create `stack_frame.rs`
- refactor: move the definition of `StackFrame` to `stack_frame.rs`
bors r+

refactor: move the definition of `StackFrame` to `stack_frame.rs`

---

kernel/src/device/pci/xhci/port/mod.rs

chore: print before and after port reset

---

kernel/src/device/pci/xhci/exchanger/transfer.rs

256 is too small for my laptop.
bors r+

fix: increase the size of the buffer for the USB conf descriptor

---

kernel/src/graphics/screen/log.rs

chore: start logging from the top of the screen

---

kernel/src/device/pci/xhci/port/slot.rs

chore: improve the error message

---

kernel/src/device/pci/xhci/structures/registers/mod.rs

refactor: shorten variable names

---

kernel/src/lib.rs
kernel/src/process/mod.rs

test: add a test to ensure the timer works correctly

---

kernel/Cargo.toml
kernel/src/graphics/screen/writer.rs

feat: scroll logs

---

kernel/Cargo.toml
kernel/src/graphics/screen/writer.rs

Reverts toku-sa-n/ramen#552
#551 didn't work on my desktop. To revert it, this PR also should be reverted.
bors r+

Revert "feat: scroll logs"

---

kernel/src/graphics/mod.rs
kernel/src/graphics/screen/layer.rs
kernel/src/graphics/screen/writer.rs
kernel/src/interrupt/timer.rs
kernel/src/lib.rs

Reverts toku-sa-n/ramen#551
Didn't work on my desktop.
bors r+

Revert "feat: implement double buffering"

---

kernel/src/lib.rs
kernel/src/process/mod.rs
kernel/src/tests/mod.rs
kernel/src/tests/process.rs

- chore: create `tests` module
- chore: add the test main function
- chore: add a test process if the OS is built for testing
- chore: move the process switch test into `tests/process.rs`
Fixes: #558 
bors r+

chore: add a test process

---

.github/workflows/test.yml
Makefile
kernel/src/lib.rs

build: deny all warnings

---

kernel/src/mem/allocator/mod.rs

- fix: wrong implementation of `deallocate_pages`
- refactor: split into two functions
Fixes: #535 
bors r+

fix: `deallocate_pages` was implemented incorrectly

---

kernel/src/mem/allocator/mod.rs
kernel/src/syscall.rs

- chore: return `None` if allocation fails
- refactor: split into functions
bors r+

refactor: `allocate_pages`

---

kernel/src/device/pci/xhci/structures/scratchpad.rs

fix: the address of an array was aligned wrongly

---

kernel/src/device/pci/xhci/structures/descriptor.rs

fix: wrong endpoint type was specified

---

bootx64/Cargo.toml
common/Cargo.toml
kernel/Cargo.toml
kernel/src/mem/allocator/mod.rs
kernel/src/mem/allocator/page_box.rs
kernel/src/mem/allocator/virt.rs
syscalls/Cargo.toml

chore: update the versions of dependencies

---

kernel/src/device/pci/xhci/mod.rs
kernel/src/device/pci/xhci/structures/registers/operational.rs
kernel/src/device/pci/xhci/xhc.rs

chore: ensure that no error occurs on xHC

---

kernel/src/graphics/mod.rs
kernel/src/graphics/screen/layer.rs
kernel/src/graphics/screen/writer.rs

- chore: add `id` as a member of `Writer`
- chore: define `set_pixel`
- chore: write logs on a layer
- chore: remove unused lines
Fixes: #576 
bors r+

chore: print logs on a layer

---

common/src/vram.rs
kernel/Cargo.toml
kernel/src/graphics/font.rs
kernel/src/graphics/mod.rs
kernel/src/graphics/screen/cursor.rs
kernel/src/graphics/screen/layer.rs
kernel/src/graphics/screen/writer.rs

- chore: update the version of `screen_layer`
- chore: change types to the proper ones
Fixes: #553 
bors r+

chore: change types to the proper ones

---

kernel/src/device/pci/ahci/port/command_list.rs
kernel/src/device/pci/ahci/port/received_fis.rs
kernel/src/device/pci/xhci/exchanger/transfer.rs
kernel/src/device/pci/xhci/port/class_driver/keyboard.rs
kernel/src/device/pci/xhci/port/class_driver/mouse.rs
kernel/src/device/pci/xhci/structures/context.rs
kernel/src/device/pci/xhci/structures/dcbaa.rs
kernel/src/device/pci/xhci/structures/ring/command/mod.rs
kernel/src/device/pci/xhci/structures/ring/event/mod.rs
kernel/src/device/pci/xhci/structures/ring/event/segment_table.rs
kernel/src/device/pci/xhci/structures/ring/transfer/mod.rs
kernel/src/device/pci/xhci/structures/scratchpad.rs
kernel/src/fs/ustar.rs
kernel/src/mem/allocator/page_box.rs
kernel/src/process/mod.rs

chore: rename `PageBox::new(_slice)?` to `PageBox::user(_slice)?`

---

bootx64/Cargo.toml
common/Cargo.toml
kernel/Cargo.toml
syscalls/Cargo.toml

chore: update dependencies

---

kernel/src/process/creator.rs
kernel/src/process/manager.rs
kernel/src/process/mod.rs

feat: implement PID

---

kernel/src/gdt.rs
kernel/src/lib.rs
kernel/src/process/manager.rs
kernel/src/process/mod.rs
kernel/src/process/stack_frame.rs
kernel/src/tests/process.rs

- refactor: rename to `user`
- chore: define `kernel` function
- refactor: define `Selectors`
- refactor: rename to `Process::user`
- chore: add `privilege` as a member of `Process`
- chore: define `Process::kernel`
- refactor: define `Process::new`
- chore: create a stack frame depending on process' privilege level
- test: add a kernel privilege process test task
Fixes: #598 
bors r+

feat: create kernel privilege process

---

kernel/src/process/manager.rs
kernel/src/process/mod.rs

fix: change the type of PID to i32

---

kernel/src/process/manager.rs
kernel/src/process/mod.rs
kernel/src/syscall.rs
syscalls/src/lib.rs

feat: implement `getpid`

---

kernel/src/lib.rs
kernel/src/process/manager.rs
kernel/src/process/mod.rs

feat: implement the process manager

---

kernel/src/process/manager.rs
kernel/src/process/mod.rs
kernel/src/process/switch.rs

- chore: create `switch.rs`
- refactor: move codes of switching processes to `switch` module
bors r+

refactor: create `switch` module

---

kernel/src/lib.rs
kernel/src/process/manager.rs
kernel/src/process/mod.rs

fix: create PML4 in the address space of the process manager

---

kernel/src/device/pci/xhci/port/endpoint.rs
kernel/src/device/pci/xhci/port/slot.rs
kernel/src/device/pci/xhci/structures/registers/operational.rs

fix: select proper max packet size

---

kernel/src/process/manager.rs
kernel/src/process/stack_frame.rs
kernel/src/process/switch.rs

- fix: the order of registers to be pushed
- chore: create a process loader
Fixes: #618 
bors r+

chore: create the process loader

---

kernel/src/lib.rs
kernel/src/process/collections/process.rs
kernel/src/process/collections/woken_pid.rs
kernel/src/process/exit.rs
kernel/src/process/manager.rs
kernel/src/process/mod.rs
kernel/src/syscall.rs
kernel/src/tests/process.rs
syscalls/src/lib.rs

- feat: implement `exit` system call
- test: add a process to test `exit` system call
Fixes: #620 
bors r+

feat: implement `exit` system call

---

kernel/src/device/pci/xhci/port/class_driver/keyboard.rs
kernel/src/device/pci/xhci/port/class_driver/mouse.rs
kernel/src/device/pci/xhci/port/mod.rs

refactor: create struct instances in each task

---

.github/workflows/test.yml
Makefile
kernel/Cargo.toml

Refactor build process

---

kernel/src/device/pci/xhci/structures/ring/command/trb.rs
kernel/src/device/pci/xhci/structures/ring/event/trb/completion.rs
kernel/src/device/pci/xhci/structures/ring/event/trb/mod.rs
kernel/src/device/pci/xhci/structures/ring/mod.rs
kernel/src/device/pci/xhci/structures/ring/transfer/trb/control.rs
kernel/src/device/pci/xhci/structures/ring/transfer/trb/mod.rs

refactor: `add_trb` also takes the ID for the TRB

---

kernel/src/device/pci/xhci/structures/ring/command/trb.rs
kernel/src/device/pci/xhci/structures/ring/event/trb/mod.rs
kernel/src/device/pci/xhci/structures/ring/mod.rs
kernel/src/device/pci/xhci/structures/ring/transfer/trb/control.rs
kernel/src/device/pci/xhci/structures/ring/transfer/trb/mod.rs

refactor: implement `Default` with macro

---

Makefile
kernel/src/lib.rs
kernel/src/process/manager.rs
kernel/src/process/mod.rs
kernel/src/process/stack_frame.rs
kernel/src/tests/mod.rs
kernel/src/tests/process.rs

feat: allow processes to return

---

kernel/src/graphics/vram.rs

fix: the length of the VRAM was wrongly calculated

---

kernel/src/graphics/vram.rs
kernel/src/graphics/writer.rs

refactor: specify each pixel by indexing

---

kernel/src/device/pci/xhci/structures/ring/event/mod.rs
kernel/src/device/pci/xhci/structures/ring/event/trb/completion.rs

chore: print the completion code of the Completion TRBs

---

kernel/src/device/pci/xhci/port/mod.rs
kernel/src/device/pci/xhci/structures/context.rs

refactor: use `default`

---

apps/tsukemen/Cargo.toml
apps/tsukemen/src/lib.rs
kernel/Cargo.toml
kernel/src/lib.rs

chore: add a test application named "tsukemen"

---

kernel/src/device/pci/xhci/structures/context.rs

refactor: use non-macro version of bitfield

---

kernel/src/device/pci/xhci/port/slot.rs
kernel/src/device/pci/xhci/structures/context.rs

refactor: rename to `output`

---

kernel/src/device/pci/xhci/exchanger/command.rs
kernel/src/device/pci/xhci/exchanger/receiver.rs
kernel/src/device/pci/xhci/exchanger/transfer.rs
kernel/src/device/pci/xhci/mod.rs
kernel/src/device/pci/xhci/port/mod.rs
kernel/src/device/pci/xhci/port/slot.rs
kernel/src/device/pci/xhci/port/spawner.rs
kernel/src/device/pci/xhci/structures/ring/event/mod.rs

- refactor: shorten the name of a variable
- refactor: make `Receiver` static
bors r+

refactor: make `Receiver` static

---

kernel/src/device/pci/xhci/port/endpoint.rs
kernel/src/device/pci/xhci/port/slot.rs

refactor: define getters

---

kernel/src/device/pci/xhci/exchanger/receiver.rs
kernel/src/device/pci/xhci/mod.rs

refactor: remove an unused `Default` implementation

---

kernel/src/device/pci/xhci/exchanger/command.rs
kernel/src/device/pci/xhci/mod.rs
kernel/src/device/pci/xhci/port/endpoint.rs
kernel/src/device/pci/xhci/port/mod.rs
kernel/src/device/pci/xhci/port/slot.rs
kernel/src/device/pci/xhci/port/spawner.rs
kernel/src/lib.rs

refactor: make `Sender` static

---

kernel/src/syscall.rs
kernel/src/tests/mod.rs
kernel/src/tests/syscall.rs
syscalls/src/lib.rs

`PageBox` needs this system call.
bors r+

feat: add `translate_address` system call

---

kernel/src/device/pci/xhci/port/class_driver/keyboard.rs
kernel/src/device/pci/xhci/port/class_driver/mouse.rs
kernel/src/device/pci/xhci/port/endpoint.rs

refactor: implement `issue_normal_trb` for `endpoint::Collection`

---

kernel/src/tests/mem.rs
page_box/src/lib.rs

chore: implement `From<&[T]>` for `PageBox`

---

kernel/src/device/pci/ahci/port/command_list.rs
kernel/src/device/pci/ahci/port/received_fis.rs
kernel/src/device/pci/xhci/exchanger/transfer.rs
kernel/src/device/pci/xhci/port/class_driver/keyboard.rs
kernel/src/device/pci/xhci/port/class_driver/mouse.rs
kernel/src/device/pci/xhci/structures/context.rs
kernel/src/process/mod.rs
kernel/src/process/page_table.rs
kernel/src/tests/mem.rs
kernel/src/tests/syscall.rs
page_box/src/lib.rs

refactor: replace `PageBox::new` with `PageBox::from`

---

kernel/Cargo.toml
kernel/src/device/pci/ahci/registers/generic.rs
kernel/src/device/pci/ahci/registers/port.rs
kernel/src/device/pci/xhci/port/endpoint.rs
kernel/src/device/pci/xhci/port/mod.rs
kernel/src/device/pci/xhci/port/resetter.rs
kernel/src/device/pci/xhci/structures/registers/capability.rs
kernel/src/device/pci/xhci/structures/registers/doorbell.rs
kernel/src/device/pci/xhci/structures/registers/extended_capability.rs
kernel/src/device/pci/xhci/structures/registers/operational.rs
kernel/src/device/pci/xhci/structures/registers/runtime.rs
kernel/src/interrupt/apic/io.rs
kernel/src/interrupt/apic/local.rs
kernel/src/interrupt/timer.rs
kernel/src/mem/accessor.rs

refactor: rewrite with `accessor` crate

---

kernel/Cargo.toml
kernel/src/interrupt/apic/io.rs
kernel/src/mem/accessor.rs

chore: update the version of `accessor` crate

---

kernel/Cargo.toml
kernel/src/device/pci/xhci/port/class_driver/keyboard.rs
kernel/src/device/pci/xhci/port/class_driver/mouse.rs
kernel/src/device/pci/xhci/port/context.rs
kernel/src/device/pci/xhci/port/endpoint.rs
kernel/src/device/pci/xhci/port/mod.rs
kernel/src/device/pci/xhci/port/slot.rs
kernel/src/device/pci/xhci/structures/context.rs
kernel/src/device/pci/xhci/structures/dcbaa.rs
kernel/src/device/pci/xhci/structures/descriptor.rs
kernel/src/device/pci/xhci/structures/ring/command/mod.rs
kernel/src/device/pci/xhci/structures/ring/event/mod.rs

refactor: rewrite with the `xhci` crate of the version 0.3.0

---

kernel/Cargo.toml
kernel/src/device/pci/ahci/registers/generic.rs
kernel/src/device/pci/ahci/registers/port.rs
kernel/src/device/pci/xhci/structures/registers.rs
kernel/src/interrupt/apic/io.rs
kernel/src/interrupt/apic/local.rs
kernel/src/interrupt/timer.rs
kernel/src/mem/accessor.rs

chore: update the versions of the dependencies

---

bootx64/Cargo.toml
common/Cargo.toml
kernel/Cargo.toml
kernel/src/lib.rs
page_box/Cargo.toml
page_box/src/lib.rs
syscalls/Cargo.toml
syscalls/src/lib.rs
terminal/Cargo.toml

fix: build error on the latest nightly

---

.github/dependabot.yml

fix: add missing dependency settings

---

common/Cargo.toml
kernel/Cargo.toml
terminal/Cargo.toml

chore(deps): update versions of dependencies

---

kernel/src/device/pci/xhci/port/mod.rs

refactor: define the `init_port_and_slot_exclusively` function

---

bootx64/Cargo.toml
bootx64/src/gop.rs
common/Cargo.toml
kernel/Cargo.toml

chore(deps): update the version of `uefi` crate

---

kernel/src/device/pci/xhci/exchanger/command.rs

chore: panic if an error occurs in sending the Command TRB

---

kernel/src/syscall.rs
syscalls/src/lib.rs

- refactor: remove the unnecessary blank line
- chore: add the 3rd argument for the systemcalls
bors r+

chore: add the 3rd parameter for the system calls

---

kernel/src/interrupt/handler.rs

fix: missing explanation

---

kernel/src/process/collections/process.rs
kernel/src/process/manager.rs
kernel/src/process/message.rs
kernel/src/process/mod.rs
kernel/src/syscall.rs
syscalls/src/lib.rs

- chore: add the `message.rs`
- chore: define functions to handle a process
- chore: add the definition of the `send` and `receive` functions
- fix: forgot to mark as mutable
- chore: add the `notify_exists` system call
- refactor: remove the unused functions
bors r+

feat: implement the `notify_exists` system call

---

kernel/src/interrupt/handler.rs
kernel/src/interrupt/mod.rs
kernel/src/syscall.rs
syscalls/src/lib.rs

feat: implement the `notify_on_interrupt` system call

---

kernel/Cargo.toml
kernel/src/device/mod.rs
kernel/src/interrupt/handler.rs
kernel/src/lib.rs
ps2_mouse/Cargo.toml
ps2_mouse/src/lib.rs

feat: implement the PS/2 mouse process

---

Makefile

chore: exit the clippy check on error

---

bootx64/.cargo/config.toml
bootx64/src/fs/mod.rs
bootx64/src/lib.rs

refactor: get a file size from the `get_info` method

---

kernel/src/lib.rs
kernel/src/panic.rs
kernel/src/qemu.rs
kernel/src/tests/mod.rs

- chore: exit QEMU on panic
- refactor: create the `qemu` module
bors r+

chore: exit the QEMU on panic

---

kernel/src/panic.rs
kernel/src/qemu.rs
kernel/src/tests/mod.rs

fix: exit as a failure on panic

---

apps/tsukemen/Cargo.toml
apps/tsukemen/src/lib.rs
kernel/Cargo.toml
kernel/src/lib.rs

There is no plan to continue developing this app.
bors r+

refactor: remove `tsukemen` app

---

kernel/src/device/pci/xhci/exchanger/transfer.rs
kernel/src/device/pci/xhci/port/class_driver/mouse.rs
kernel/src/device/pci/xhci/port/endpoint.rs
kernel/src/device/pci/xhci/port/init/descriptor_fetcher.rs
kernel/src/device/pci/xhci/port/init/endpoints_initializer.rs
kernel/src/device/pci/xhci/port/init/fully_operational.rs
kernel/src/device/pci/xhci/port/mod.rs
kernel/src/device/pci/xhci/structures/descriptor.rs

chore: issue Set Configuration

---

kernel/src/device/pci/xhci/exchanger/transfer.rs
kernel/src/device/pci/xhci/port/class_driver/mouse.rs
kernel/src/device/pci/xhci/port/endpoint.rs
kernel/src/device/pci/xhci/port/init/fully_operational.rs

chore: send the Set Idle request

---

kernel/Cargo.toml
kernel/src/device/pci/xhci/exchanger/command.rs
kernel/src/device/pci/xhci/exchanger/transfer.rs

- refactor: use `into` to decrease the number of lines
- refactor: use `into` to decrease the number of lines
bors r+

refactor: use `into` to convert to `Allowed`

---

kernel/src/device/pci/xhci/exchanger/command.rs
kernel/src/device/pci/xhci/exchanger/transfer.rs

- refactor: define the `Channel` struct
- refactor: define the `Channel` struct
bors r+

refactor: define the `Channel` structs

---

kernel/src/device/pci/xhci/exchanger/transfer.rs

refactor: use `into` to reduce the number of lines

---

kernel/src/panic.rs

chore: chore: print the default panic information

---

kernel/src/device/pci/xhci/exchanger/transfer.rs
kernel/src/device/pci/xhci/port/class_driver/mouse.rs
kernel/src/device/pci/xhci/port/endpoint.rs
kernel/src/device/pci/xhci/port/init/fully_operational.rs

chore: send the Set Protocol request

---

kernel/kernel.ld
kernel/src/gdt.rs
kernel/src/lib.rs
kernel/src/mem/allocator/kpbox.rs
kernel/src/mem/allocator/mod.rs
kernel/src/process/collections/process.rs
kernel/src/process/exit.rs
kernel/src/process/manager.rs
kernel/src/process/mod.rs
kernel/src/process/page_table.rs

- chore: add the `kpbox` module
- chore: remove the process manager process
- chore: remove the exited process
- refactor: remove the unused lines
bors r+

chore: remove the process manager process

---

kernel/src/interrupt/handler.rs
kernel/src/interrupt/idt.rs
kernel/src/process/manager.rs
kernel/src/syscall.rs
syscalls/src/lib.rs

refactor: remove the unused lines

---

kernel/src/lib.rs

refactor: remove the unnecessary function

---

kernel/src/device/pci/xhci/port/init/endpoints_initializer.rs

refactor: remove the unnecessary attribute

---

kernel/src/device/pci/xhci/port/endpoint.rs

refactor: reorder structs

---

kernel/src/device/pci/xhci/port/endpoint.rs
kernel/src/device/pci/xhci/port/init/endpoints_initializer.rs

refactor: move the initialization code to `endpoint_initializer.rs`

---

kernel/src/device/pci/xhci/port/class_driver/mouse.rs
kernel/src/device/pci/xhci/port/init/descriptor_fetcher.rs
kernel/src/device/pci/xhci/port/init/endpoints_initializer.rs
kernel/src/device/pci/xhci/port/init/max_packet_size_setter.rs
kernel/src/device/pci/xhci/port/init/slot_structures_initializer.rs

- chore: set the correct interval value
- refactor: rename a variable name
- chore: allow too many arguments
bors r+

chore: set the correct interval value

---

kernel/src/device/pci/xhci/port/class_driver/mass_storage/mod.rs

fix: forgot to configure the mass storage device

---

.github/workflows/test.yml
Makefile
kernel/Cargo.toml

- chore: add a command to detect unused dependencies
- ci: detect unused dependencies
Fixes: #665
bors r+

ci: detect unused dependencies

---

kernel/src/lib.rs

refactor: integrate feature and clippy attributes

---

kernel/src/device/pci/xhci/port/class_driver/mass_storage/mod.rs
kernel/src/device/pci/xhci/port/class_driver/mass_storage/scsi/mod.rs
kernel/src/device/pci/xhci/port/init/fully_operational.rs

chore: write `0x334` to the USB mass storage device

---

kernel/src/process/collections/process.rs

Using `BTreeMap` is not a proper way because the process manager manages the PIDs of processes.
bors r+

refactor: use `Vec` for the collection of processes

---

kernel/src/process/collections/process.rs

Reverts toku-sa-n/ramen#744
Using the index of `Vec` is not stable because the index may change on the removal of an element, for example. It may better to prepare IDs for each process in the kernel and use it to identify the sender and the receiver. This is redundant because PID exists, though.
bors r+

Revert "refactor: use `Vec` for the collection of processes"

---

kernel/src/tests/process/ipc.rs
message/src/lib.rs

chore: add a header for messages

---

Makefile

test: do not `make clean` before doing a test

---

kernel/src/device/pci/xhci/port/class_driver/mass_storage/scsi/mod.rs

refactor: define `Command` enum

---

kernel/src/device/pci/xhci/port/class_driver/mass_storage/scsi/channel.rs
kernel/src/device/pci/xhci/port/class_driver/mass_storage/scsi/command.rs
kernel/src/device/pci/xhci/port/class_driver/mass_storage/scsi/mod.rs

refactor: remove the unused files

---

kernel/Cargo.toml
kernel/src/device/pci/xhci/port/class_driver/mass_storage/mod.rs
kernel/src/device/pci/xhci/port/class_driver/mass_storage/scsi/command_data_block.rs
kernel/src/device/pci/xhci/port/class_driver/mass_storage/scsi/mod.rs

- refactor: define CDB as an enum
- refactor: define a macro
bors r+

refactor: define the CDB structure as an enum

---

kernel/src/device/pci/xhci/port/class_driver/mass_storage/mod.rs
kernel/src/device/pci/xhci/port/class_driver/mass_storage/scsi/mod.rs

refactor: define `Flags` enum

---

kernel/src/device/pci/xhci/port/class_driver/mass_storage/mod.rs

refactor: define `LEN` constant value

---

kernel/src/device/pci/xhci/port/class_driver/mass_storage/mod.rs
kernel/src/device/pci/xhci/port/class_driver/mass_storage/scsi/response.rs

Read Capacity 16 also exists.
bors r+

refactor: rename to the Read Capacity 10

---

kernel/src/device/pci/xhci/port/class_driver/mass_storage/scsi/response.rs

chore: fetch the capacity of a storage

---

kernel/src/device/pci/xhci/port/class_driver/keyboard.rs

fix: forgot to configure the USB keyboard

---

kernel/src/device/pci/xhci/port/class_driver/keyboard.rs

chore: set the Boot protocol for USB keyboard

---

kernel/src/process/collections/process.rs
kernel/src/process/ipc.rs
kernel/src/process/mod.rs
kernel/src/process/slot_id.rs
kernel/src/syscall.rs

- chore: add the `slot_id` module
- chore: define the generator of the slot ID
bors r+

chore: define the generator of the Slot ID

---

kernel/src/device/pci/xhci/port/init/fully_operational.rs

fix: the order of parameters should be consistent

---

.github/workflows/test.yml
Makefile
run_qemu.sh

test: build a binary for testing correctly

---

run_qemu.sh

style: apply formatter

---

Makefile
run_qemu.sh

- chore: change the `all` target to `IMG_FILE`
- refactor: define the `create_storage_image` function
bors r+

refactor: `run_qemu.sh`

---

Makefile

refactor: remove the unused variable

---

run_qemu.sh

chore: exit `run_qemu.sh` on error

---

bootx64/src/mem/paging.rs
common/src/constant.rs
kernel/src/process/page_table.rs

fix: use the 510th entry as the recursive paging

---

kernel/src/lib.rs

refactor: remove the outdated comments

---

kernel/src/lib.rs
kernel/src/mem/allocator/phys.rs

refactor: narrow the scope of functions

---

kernel/src/mem/allocator/mod.rs
kernel/src/mem/allocator/phys.rs
kernel/src/mem/mod.rs

It is shorter than method callings.
bors r+

refactor: add functions to handle a static

---

kernel/src/mem/allocator/phys.rs

refactor: define `is_mergable` method

---

kernel/src/mem/allocator/phys.rs

chore: use `assert`

---

kernel/src/lib.rs
kernel/src/mem/allocator/phys.rs
kernel/src/mem/mod.rs

refactor: define the `mem::init` function

---

.github/workflows/test.yml

ci: cache the Cargo data

---

.github/workflows/test.yml

fix(ci): specify working directories

---

frame_manager/src/lib.rs

refactor: reorder lines

---

bootx64/Cargo.toml
common/Cargo.toml
frame_manager/Cargo.toml
kernel/Cargo.toml
page_box/Cargo.toml
syscalls/Cargo.toml

chore(deps): update the version of the `os_units` crate

---

kernel/src/lib.rs

chore: initialize the terminal as soon as possible

---

Makefile
example_server/.cargo/config.toml
example_server/Cargo.toml
example_server/src/lib.rs
example_server/x86_64-unknown-ramen.json
kernel/Cargo.toml
kernel/build.rs
kernel/src/initrd.s

- chore: add an example server
- feat: append the initrd file to the kernel
bors r+

feat: append the initrd file to the kernel

---

kernel/Cargo.toml
kernel/src/fs.rs
kernel/src/initrd.s
kernel/src/lib.rs

- chore: add the `fs` module
- feat: print the name of files in the initrd
bors r+

feat: list the name of files in the initrd

---

.github/workflows/audit.yml

ci: run `cargo audit` every day

---

kernel/src/syscall.rs

System calls which operates the I/O ports are now handled by the port
server, not the kernel itself.
bors r+

refactor: remove the unreachable lines

---

pm/src/lib.rs

refactor: create a new function

---

pm/src/lib.rs

refactor: define `ProcessCollection`

---

pm/src/lib.rs

chore: panic when the process manager receives an unexpected message

---

README.md

fix: obsolete building commands

---

kernel/src/lib.rs
kernel/src/process/collections/process.rs

chore: remove the stabilized and removed features

---

kernel/src/lib.rs
kernel/src/process/mod.rs

feat: the processes have their names

---

kernel/src/process/page_table.rs

refactor: use `impl Sized?`

---

kernel/Cargo.toml
kernel/src/fs.rs
kernel/src/lib.rs
kernel/src/process/mod.rs
kernel/src/process/page_table.rs

- chore: add the `content` method
- feat: load a binary from initrd
- refactor: avoid to use similar name
bors r+

feat: load an ELF file from initrd

---

.github/workflows/test.yml

ci: relax the time limit of test

---

Makefile
kernel/Cargo.toml
kernel/src/fs.rs
kernel/src/lib.rs
kernel/src/process/page_table.rs
pm/.cargo/config.toml
pm/Cargo.toml
pm/src/lib.rs
pm/x86_64-unknown-ramen.json
ralib/Cargo.toml
ralib/src/lib.rs

feat: create the PM binary

---

run_qemu.sh

- chore: add a GPT image
- chore: update
- chore: use the GPT image for a USB mass storage device emulation
bors r+

chore: create a GPT image

---

.github/stale.yml

To make it easier to manage issues.

chore: enable the `Stale` bot

---

kernel/src/syscall.rs

To reduce the level of indents.
bors r+

refactor: define the `select_proper_syscall_unchecked` function

---

kernel/src/lib.rs

refactor: remove an unnecessary feature

---

kernel/src/mem/mod.rs

refactor: limit the scope of functions

---

kernel/src/process/page_table.rs

fix: wrong management of page tables of processes

---

Makefile

chore: `make` now tracks changes on the Rust project

---

ralib/Cargo.toml
ralib/src/io.rs
ralib/src/lib.rs

Reverts toku-sa-n/ramen#850
Fixes: #853, although this is not a perfect way.

Revert "feat: implement logging feature for `ralib`"

---

kernel/src/fs.rs
kernel/src/process/mod.rs
kernel/src/process/page_table.rs
ralib/Cargo.toml
ralib/src/io.rs
ralib/src/lib.rs

Reverts toku-sa-n/ramen#855
Second try.
Fixes: #853

Revert "Revert "feat: implement logging feature for `ralib`""

---

.github/workflows/test.yml

fix(ci): renamed lint name

---

kernel/src/lib.rs
kernel/src/process/mod.rs

refactor(process) rename `process::add`

---

kernel/src/process/mod.rs
kernel/src/process/page_table.rs
kernel/src/process/switch.rs

refactor(process): save the pml4 frame

---

kernel/src/panic.rs

fix: prevent interrupts on panic

---

kernel/src/process/ipc.rs

chore(ipc): prevent from contacting with self

---

bootx64/src/main.rs
libs/common/src/constant.rs

The constant value is used only once.

refactor: inline the kernel name

---

Makefile

Not to cause any problematic things.

chore: `make clean` runs `cargo clean`

---

Cargo.lock
bootx64/src/jump.rs
bootx64/src/lib.rs
kernel/Cargo.toml
kernel/src/lib.rs
libs/boot_info/Cargo.toml
libs/boot_info/src/lib.rs
libs/predefined_mmap/src/lib.rs

To remove some constant values.

chore: improve the kernel jump mechanism

---

kernel/src/process/mod.rs
kernel/src/process/scheduler.rs
kernel/src/syscall.rs
libs/syscalls/src/lib.rs

It turned out that implementing the exit system call is super difficult
for me.

chore: remove the exit system call
