boot/Makefile

-O2 causes the error of "undefined memset".

[Change]Use -O1 instead of -O2 for building EFI file

---

bochsrc

Bochs does not support UEFI booting.

[Change]Remove bochsrc

---

Makefile

Using `mount` needs `sudo`, regardless of the permission of the file or device.  Using `mmd` and `mcopy` is the only way to edit fat images without `sudo`.
Fixes: #14

Use `mmd` and `mcopy`

---

src/asm.rs
src/descriptor_table.rs
src/gdt.rs

These functions are used in limited ways.
Fixes: #17

[Refactoring]Move lidt and lgdt and related functions

---

bootx64/src/main.rs

`mod debug` must come before all other modules.

[Fix]Unable to use debug macros in another modules

---

src/graphics/mod.rs

Not to drop the old values.
Fixes: #37

[Change]Use ptr::write instead of dereferencing

---

bootx64/src/exit.rs
bootx64/src/fs.rs
bootx64/src/fs/kernel_bytes.rs

Using the absolute value should be avoided.

Read memory bytes

---

bootx64/src/exit.rs
bootx64/src/fs.rs
bootx64/src/fs/kernel_bytes.rs
bootx64/src/main.rs
bootx64/src/mem/paging.rs
common_items/src/addr.rs
common_items/src/lib.rs
common_items/src/size.rs

Difficult to replace all `usize`s to `Addr` and `Size` at once. Not all these types are replaced.

Define addrs and size structs in common items

---

bootx64/src/exit.rs
bootx64/src/fs.rs
bootx64/src/fs/kernel_bytes.rs
bootx64/src/mem/paging.rs
common_items/src/addr.rs

You don't have to type `<` and `>` and include `Addr`.
Fixes: #76

Define `PhysAddr` and `VirtAddr`

---

bootx64/src/exit.rs
bootx64/src/main.rs
common/Cargo.toml
common/src/boot.rs
kernel/Cargo.toml
kernel/src/lib.rs

The address of the entry point of the kernel wasn't saved. This commit makes `boot::Info` include the address so that it will also be saved.
Fixes: #139

Fix the crash on release build

---

kernel/memlib/lib.c

Eventually, this function will be used by rustc.

[Add]memcmp

---

kernel/src/lib.rs
kernel/src/mem/allocator/heap.rs
kernel/src/mem/allocator/mod.rs
kernel/src/mem/allocator/phys.rs

Split `allocator` module into `phys` and `heap`

---

kernel/src/mem/allocator/virt.rs

This function is useful when tackling with PCI and XHCI.

Add `map_temporary` function

---

bors.toml

This reverts commit 72195c5ec6d77f568471ede4fafbae01aa5c2580.
This operation was not what I thought.
bors r+

Revert "Use squash merge (#231)"

---

bootx64/src/mem/paging.rs
common/src/kernelboot.rs
common/src/mem/mod.rs
kernel/src/lib.rs
kernel/src/mem/allocator/heap.rs

- Rename to `as_mut_slice`
- Rename to `mem_map_mut`
- Initialize heap area before initializing page manager
To use `alloc` crate for initializing page manager. Fixes: #225
bors r+

Initialize heap manager first

---

kernel/src/device/pci/xhci/mod.rs
kernel/src/mem/allocator/mod.rs
kernel/src/mem/allocator/page_box.rs

- Define `page_box` module
- Define `PageBox` type
- Define `PageBox` for slice
- Make `new_slice` public
- Define `PageBox::phys_addr`
- Use `PageBox` for DCBAA
- Remove unnecessary imports
`slice::Accessor` is still remaining because if will not drop physical pages while `PageBox` will.
bors r+

Implement `PageBox` type

---

kernel/src/device/pci/xhci/ring/command.rs
kernel/src/device/pci/xhci/ring/mod.rs
kernel/src/device/pci/xhci/ring/trb.rs

- Make it possible to generate `Raw` from `u128`
- Remove `len`
- Define `enqueueable`
- Define `Raw::from`
- Define `enqueue`
bors r+

Implement enqueue for command ring

---

kernel/src/device/pci/xhci/mod.rs
kernel/src/device/pci/xhci/register/doorbell.rs
kernel/src/device/pci/xhci/register/hc_capability_registers.rs
kernel/src/device/pci/xhci/register/mod.rs
kernel/src/device/pci/xhci/ring/command.rs
kernel/src/device/pci/xhci/ring/event/mod.rs
kernel/src/device/pci/xhci/ring/mod.rs
kernel/src/device/pci/xhci/ring/trb.rs

- Remove an unnecessary `pub`
- Remove an unused trait implementation
- Define `Trb::new_noop`
- Add `pub`
- Define `DoorbellOffset`
- Add `db_off` as a member
- Add `doorbell` module
- Define doorbell array
- Define `notify_to_hc`
- Add `door_bell` as a member
- Issue an event ring
To confirm that the event and command ring work properly.
bors r+

Sent No op TRB

---

kernel/src/device/pci/xhci/ring/raw.rs
kernel/src/device/pci/xhci/ring/trb.rs

To prevent from forgetting to change parts of codes.
bors r+

Remove `Ty` type

---

bootx64/src/exit.rs
bootx64/src/main.rs
bootx64/src/mem/paging.rs
common/src/kernelboot.rs

This is not used by the kernel.
bors r+

Remove `reserved` from boot information

---

kernel/src/device/mouse.rs

This synchronization is useless because the satisfaction of this
equation does not mean the synchronization is complete.
bors r+

Remove an unnecessary sync

---

kernel/src/device/pci/xhci/ring/event/mod.rs
kernel/src/device/pci/xhci/ring/trb.rs

- Define `phys_addr_to_next_trb`
- Increment event ring dequeue pointer after dequeue
bors r+

Increment event ring dequeue pointer

---

kernel/src/device/pci/xhci/mod.rs
kernel/src/device/pci/xhci/ring/command.rs

- Add `registers` as a member of the command ring
- Split `command_ring` from `xhci`
bors r+

Split `command_ring` member

---

kernel/src/device/pci/xhci/mod.rs

Only `hc_operational` is needed.
bors r+

Get `hc_operational`, not `registers`

---

kernel/src/device/pci/xhci/register/hc_capability.rs

Stop to print xHCI version

---

kernel/src/device/pci/xhci/dcbaa.rs
kernel/src/device/pci/xhci/mod.rs
kernel/src/device/pci/xhci/ring/command.rs
kernel/src/device/pci/xhci/ring/event/mod.rs

- Run xHC after all components are initialized
- Remove unnecessary `let` bindings
bors r+

Fix codes of xHC resetting

---

kernel/src/device/pci/xhci/register/hc_operational.rs
kernel/src/device/pci/xhci/ring/command.rs

- Define `init_command_ring_cycle_state`
- Rename to `set_initial_command_ring_cycle_state`
- Reduce the number of lines
bors r+

Set command ring cycle state

---

README.md

It is no longer needed.
bors r+

docs: remove `nasm` dependency

---

kernel/src/device/mouse.rs
kernel/src/device/pci/xhci/dcbaa.rs
kernel/src/device/pci/xhci/mod.rs
kernel/src/device/pci/xhci/port.rs
kernel/src/device/pci/xhci/ring/command.rs
kernel/src/device/pci/xhci/ring/event/mod.rs

To share this with multiple tasks. `Rc` may be replaced with `Arc`.
`RefCell` may be replaced with `Spinlock` in order to wait until the
lock is freed while using `RefCell` will panic.
bors r+

refactor: wrap `registers` with `Rc` and `RefCell`

---

kernel/Cargo.toml
kernel/src/device/pci/xhci/command_runner.rs
kernel/src/device/pci/xhci/mod.rs
kernel/src/device/pci/xhci/port.rs
kernel/src/device/pci/xhci/ring/command.rs
kernel/src/device/pci/xhci/ring/event/mod.rs
kernel/src/device/pci/xhci/ring/mod.rs
kernel/src/device/pci/xhci/ring/trb.rs

- chore: `send_noop` returns the address to noop trb
- chore: add command runner
- refactor: use `ok_or`
- fix: resolve dead lock
bors r+
Fixes: #317

Define the command runner

---

kernel/src/device/pci/xhci/device_slot.rs
kernel/src/device/pci/xhci/mod.rs
kernel/src/device/pci/xhci/port.rs
kernel/src/mem/allocator/page_box.rs

- chore: define `InputContext`
- refactor: define `new_from_bytes`
bors r+

Allocate input context data

---

kernel/src/device/pci/xhci/device_slot.rs
kernel/src/device/pci/xhci/port.rs
kernel/src/mem/allocator/page_box.rs

- chore: implement `DerefMut` and `Deref` for page box
- chore: init input control context
- refactor: remove an unnecessary `pub`
- refactor: define `init_input_control_context`
bors r+

Initialize the input control context

---

kernel/src/device/pci/xhci/port.rs
kernel/src/device/pci/xhci/ring/mod.rs
kernel/src/device/pci/xhci/ring/transfer.rs

- chore: allocate transfer ring
- refactor: remove an unnecessary lifetime notation
bors r+

Allocate transfer ring

---

kernel/src/device/pci/ahci/ahc/mod.rs
kernel/src/device/pci/ahci/ahc/registers/generic.rs
kernel/src/device/pci/ahci/mod.rs

- chore: add `pi` as a member
- chore: print the available ports
bors r+

Determine which ports are avilable

---

kernel/src/device/pci/ahci/ahc.rs
kernel/src/device/pci/ahci/mod.rs
kernel/src/device/pci/ahci/registers/generic.rs

- chore: define `HbaCapability`
- chore: fetch the number of command slots supported by hba
bors r+

Fetch the number of command slote supported by HBA

---

kernel/src/device/pci/ahci/mod.rs
kernel/src/device/pci/ahci/port/mod.rs
kernel/src/device/pci/ahci/registers/port.rs

- refactor: remove unnecessary member specification
- chore: add `tfd` as a member
- chore: add @ssts` as a member
- chore: add `pub`s
- refactor: remove an unnecessary `pub`
- chore: start processing of each ahci ports
- chore: moving the ownership first
bors r+

Start command list processing

---

kernel/src/device/pci/ahci/ahc.rs
kernel/src/device/pci/ahci/mod.rs
kernel/src/device/pci/ahci/port/mod.rs
kernel/src/lib.rs

- refactor: define `ports.init`
- refactor: define `Ach::init`
- refactor: remove a function
- refactor: remove unnecessary methods
- chore: spawn port tasks
bors r+

Spawn ahci port tasks

---

kernel/src/device/pci/ahci/port/mod.rs
kernel/src/device/pci/ahci/registers/port.rs

- chore: add `sact` and `ci` as members
- chore: get the index of an available command slot
bors r+

Get the index of an available command slot

---

kernel/src/device/pci/xhci/context.rs
kernel/src/device/pci/xhci/port.rs

chore: add `output_device_context` as a member

---

kernel/src/device/pci/xhci/dcbaa.rs
kernel/src/device/pci/xhci/mod.rs
kernel/src/device/pci/xhci/port.rs

- chore: add `output_device_context` as a member
- chore: change the type to `PhysAddr`
- chore: implement `Index` and `IndexMut` for DCBAA
- chore: register the address to DCBAA
- refactor: remove `TaskSpawner`
- chore: allow too many arguments
bors r+

Write an address to DCBAA

---

kernel/src/device/pci/ahci/mod.rs
kernel/src/device/pci/ahci/registers/generic.rs
kernel/src/device/pci/ahci/registers/mod.rs
kernel/src/device/pci/ahci/registers/port.rs
kernel/src/device/pci/xhci/mod.rs
kernel/src/device/pci/xhci/register/hc_capability.rs
kernel/src/device/pci/xhci/register/hc_operational.rs
kernel/src/device/pci/xhci/register/mod.rs
kernel/src/device/pci/xhci/register/runtime_base_registers.rs
kernel/src/device/pci/xhci/register/usb_legacy_support_capability.rs
kernel/src/mem/accessor.rs

fix: mark `Accessor::new(_slice)?` as unsafe

---

kernel/src/device/pci/ahci/port/command_list.rs
kernel/src/device/pci/ahci/port/mod.rs

- refactor: use `type` to define a new type
- chore: initialize command tables
bors r+

Prepare command lists

---

kernel/src/device/pci/xhci/command_runner.rs
kernel/src/device/pci/xhci/context.rs
kernel/src/device/pci/xhci/port.rs
kernel/src/device/pci/xhci/register/hc_capability.rs
kernel/src/device/pci/xhci/ring/command.rs
kernel/src/device/pci/xhci/ring/raw.rs
kernel/src/device/pci/xhci/ring/trb.rs

- chore: send an address device trb
- refactor: use `is_aligned` method
- refactor: rename to `addr_to_input_context`
- fix: wrong initialization
- chore: apply `repr`
- refactor: use `type` to wrap the internal structures
- refactor: remove unused imports
- chore: take an `PhysAddr`, not `u64`
- fix: set root hub port number
- refactor: clean codes
- refactor: define `init_device_slot`
- refactor: rename to `runner`
- refactor: rename to `control`
- refactor: use aliased types
- chore: add a message
- chore: add a method
- refactor: reorder structs
- fix: 1-indexed
bors r+

Issue an address device TRB

---

kernel/src/device/pci/xhci/ring/command.rs

- refactor: rename to `full`
- refactor: reorder methods
- refactor: remove `phys_`
- refactor: define `increment_enqueue_ptr`
- refactor: define `append_link_trb`
- refactor: define `move_enqueue_ptr_to_the_beginning`
- refactor: rename `enqueue` to `try_enqueue`
- refactor: reorder methods
- refactor: define `write_trb_on_memory`
bors r+

Refactor the code of command ring

---

kernel/src/device/pci/xhci/ring/transfer.rs

- refactor: rename `enqueue` to `try_enqueue`
- refactor: define `enqueue` method
- refactor: reorder methods
- refactor: define `write_trb_on_memory`
bors r+

Refactor code of transfer ring

---

kernel/Cargo.toml
kernel/src/device/pci/xhci/ring/raw.rs
kernel/src/device/pci/xhci/ring/trb.rs

- refactor: store TRB as `[u32; 4]`, not `u128`
- refactor: remove `NoopStructure`
- refactor: remove `CommandCompleteStructure`
- refactor: remove an unnecessary `into()`
- refactor: remove `LinkStructure`
- refactor: remove `PortStatusChangeStructure`
- refactor: remove `EnableSlotStructure`
- refactor: remove `AddressDeviceStructure`
Easier to handle slices. Didn't change unused TRBS.
bors r+

Use `bit_field` to represent TRBs

---

kernel/src/device/pci/xhci/exchanger/command.rs
kernel/src/device/pci/xhci/mod.rs

This reverts commit 0dc9a5a7672ca5398fe922f81c4559a5101ace29.
To use receiver from transfer exchanger.
bors r+

Revert "refactor: define `command::channel`"

---

kernel/src/device/pci/xhci/structures/ring/transfer/trb.rs

- refactor: rewrite `SetupStage` with `bit_flags` and `add_trb`
- refactor: rewrite `DataStage` with `bit_fields` and `add_trb`
- refactor: remove an unnecessary `into`
- refactor: rewrite `StatusStage` with `add_trb`
bors r+

Rewrite transfer TRBs with `bit_field` and `add_trb`

---

kernel/src/device/pci/xhci/structures/ring/event/trb.rs
kernel/src/device/pci/xhci/structures/ring/transfer/trb.rs

- refactor: move the definition of transfer event TRB to `event::trb`
- refactor: rewrite `TransferEvent` with `add_trb`
bors r+

Move the definition of transfer event to `event::trb`

---

kernel/Cargo.toml
kernel/src/device/pci/xhci/structures/ring/transfer/trb.rs
kernel/src/mem/allocator/page_box.rs

- chore: define `DescTy`
- chore: define `SetupStage::null`
- chore: define `Request`
- refactor: rewrite `DescTy` with enum
- chore: define `PageBox::bytes`
- chore: define `SetupStage::new_get_descriptor`
- refactor: define `DescTyIndex`
- refactor: shorten struct name
- chore: define `DataStage::null`
- chore: define `Dir`
- chore: define `DataStage::new`
- refactor: rename `Dir` to `Direction`
- chore: define `StatusStage::set_ioc`
- chore: define `StatusStage::null`
- chore: define `StatusStage`
bors r+

Define `new` method for TRBs used to get descriptor

---

kernel/src/device/pci/xhci/structures/ring/command/mod.rs
kernel/src/device/pci/xhci/structures/ring/command/trb.rs

- chore: implement `Trb::from`
- chore: define `command::Raw`
- refactor: use newly defined `Raw`
- refactor: define an unnecessary `pub`
bors r+

Split command ring into structure and manager

---

kernel/src/device/pci/xhci/structures/ring/command/mod.rs

refactor: remove an unnecessary lifetime notation

---

kernel/src/device/pci/xhci/port.rs
kernel/src/device/pci/xhci/structures/ring/transfer/mod.rs
kernel/src/device/pci/xhci/structures/ring/transfer/trb/mod.rs

- refactor: split `transfer::Ring` into two
- refactor: remove unused imports
bors r+

Split the internal structure of transfer ring

---

kernel/src/device/pci/xhci/structures/ring/command/trb.rs
kernel/src/device/pci/xhci/structures/ring/mod.rs
kernel/src/device/pci/xhci/structures/ring/transfer/mod.rs
kernel/src/device/pci/xhci/structures/ring/transfer/trb/mod.rs

- refactor: move the definition of link TRB to `ring` module
- chore: implement `new_link`
- refactor: remove an unused import
- fix: arguments
- refactor: define `set_c`
- chore: set c bit before enqueueing
bors r+

Move the definition of the Link TRB

---

kernel/src/device/pci/xhci/exchanger/command.rs
kernel/src/device/pci/xhci/structures/ring/command/mod.rs

- refactor: don't create TRBs inside Ring code
- refactor: remove unused imports
- refactor: define `issue_trb`
- fix: grammer mistake
bors r+

Create TRBs inside exchanger code

---

kernel/src/device/pci/xhci/exchanger/receiver.rs

fix: wrong position of the license notation

---

kernel/src/device/pci/xhci/port.rs
kernel/src/device/pci/xhci/structures/context.rs

- chore: define `Context`
- fix: allocate `output_device` inside page box
- refactor: rewrite with `Context`
bors r+

Define `Context` type

---

kernel/src/device/pci/xhci/port/mod.rs
kernel/src/device/pci/xhci/port/resetter.rs

- refactor: define `init_context` method
- refactor: reorder methods
- refactor: define `issue_address_device` method
- refactor: rename to `input_context_addr`
- refactor: `port` takes `u8` value
bors r+

Split a method

---

kernel/src/device/pci/xhci/port/mod.rs

To define something which handles slot.
bors r+

chore: initialize context immediately after resetting port

---

kernel/src/device/pci/xhci/exchanger/transfer.rs

refactor: create an instance of `transfer::Ring` in `Sender::new`

---

kernel/src/device/pci/xhci/exchanger/transfer.rs

- refactor: `transfer::Sender` takes `registers`
- chore: `transfer::Sender` also takes `slot_id`
- fix: forgot to write to doorbell registers after issueing TRBs
bors r+

Write to doorbell registers after issueing TRBs

---

kernel/src/device/pci/xhci/exchanger/transfer.rs

- Revert "refactor: create an instance of `transfer::Ring` in `Sender::new`"
- fix: avoid exceeding the limit of the number of arguments
bors r+

Not to create the Transfer Ring inside `transfer::Sender::new`

---

kernel/src/device/pci/xhci/mod.rs
kernel/src/device/pci/xhci/port/mod.rs
kernel/src/device/pci/xhci/structures/descriptor.rs
kernel/src/device/pci/xhci/structures/ring/event/trb/completion.rs
kernel/src/device/pci/xhci/structures/ring/transfer/mod.rs
kernel/src/device/pci/xhci/structures/ring/transfer/trb/control.rs
kernel/src/device/pci/xhci/structures/ring/transfer/trb/mod.rs

- refactor: add `command::` prefix
- chore: `Slot` takes `sender`
- chore: implement `Debug` for `descriptor::Device`
- chore: fetch the device descriptor
- fix: forgot to set the Cycle bit
- fix: set IDT flag of the Setup TRB
- fix: implement `Completion::addr`
- chore: pass an argument by reference
- refactor: remove a redundant clone
bors r+

Get the device descriptor

---

.clippy.toml
bootx64/src/fs/kernel/mod.rs
bootx64/src/main.rs
kernel/src/graphics/screen/cursor.rs
kernel/src/graphics/screen/desktop.rs
kernel/src/mem/accessor.rs
kernel/src/mem/allocator/heap.rs
kernel/src/mem/allocator/page_box.rs

- style: set the limitation of the function size
- refactor: introduce `flags` variable
- refactor: rename to `temp_allocator`
- refactor: split `init` into two functions
- refactor: introduce `flag` variable
- refactor: define `init_layer` method
- refactor: pass by `RGB8` type
- chore: allow too many lines of the method which draws the desktop
bors r+

Limit the size of functions

---

kernel/src/device/pci/xhci/structures/descriptor.rs

- chore: define `Endpoint`
- chore: `Descriptor::Endpoint` takes an `Endpoint` value
bors r+

Define `descriptor::Endpoint`

---

kernel/src/device/pci/xhci/exchanger/command.rs
kernel/src/device/pci/xhci/port/mod.rs
kernel/src/device/pci/xhci/port/slot/mod.rs
kernel/src/device/pci/xhci/structures/context.rs
kernel/src/device/pci/xhci/structures/descriptor.rs
kernel/src/device/pci/xhci/structures/ring/command/trb.rs

- chore: set A flag
- chore: add `pub`s
- chore: initialize contexts
- refactor: define `EndpointContextInitializer`
- chore: define `ConfigureEndpoint`
- chore: add `ConfigureEndpoint` as a variant
- chore: add `new_configure_endpoint`
- chore: define `configure_endpoint`
- fix: forgot to clear A1 bit
bors r+

Enable endpoint

---

kernel/src/device/pci/xhci/exchanger/transfer.rs
kernel/src/device/pci/xhci/port/context.rs
kernel/src/device/pci/xhci/port/mod.rs
kernel/src/device/pci/xhci/port/slot/endpoint.rs
kernel/src/device/pci/xhci/port/slot/mod.rs

- chore: define `endpoint::Default`
- chore: define `endpoint::Default::init_context`
- chore: `Default` does not take `slot`
- refactor: use `endpoint::Default`
- refactor: `transfer::Sender` no longer takes `ring`
- refactor: reduce the number of parameters of `endpoint::Default::new`
bors r+

Initialize the default endpoint in `Slot` struct

---

kernel/src/device/pci/xhci/port/mod.rs
kernel/src/device/pci/xhci/port/resetter.rs

refactor: `Resetter` no longer takes `Rc<RefCell>` value

---

kernel/src/device/pci/xhci/exchanger/transfer.rs
kernel/src/device/pci/xhci/port/slot/endpoint.rs
kernel/src/device/pci/xhci/port/slot/mod.rs

- chore: `endpoint::Collection` takes `def`
- refactor: remove unused imports
- chore: `Endpoint` has `sender`
- chore: clone `DoorbellWriter`
- chore: set the dequeue pointer of the Transfer Ring
bors r+

Add `sender` as a member of `Endpoint`

---

kernel/src/device/pci/xhci/exchanger/transfer.rs
kernel/src/device/pci/xhci/port/slot/mod.rs

- chore: remove `Clone` derivation
- chore: `DoorbellWriter` takes a value to write
- refactor: remove an unused member
bors r+

Add `val` to `DoorbellWriter` as a member

---

kernel/src/device/pci/xhci/mod.rs
kernel/src/device/pci/xhci/structures/ring/event/mod.rs
kernel/src/multitask/executor.rs
kernel/src/multitask/task.rs

- chore: add `polling` to `Task` as a member
- chore: let a task always woken
- refactor: let the Event ring task always wake
This task mode is used by tasks which need to poll something.
bors r+

Add a task mode "polling"

---

kernel/src/lib.rs
kernel/src/syscall.rs

- chore: create `syscall.rs`
- chore: define `syscall` method
- chore: define `syscall::register`
- fix: license notation
- chore: define `syscall::init` method
- fix: cast a function pointer to `usize`
- chore: define a wrapper of `syscall`
- chore: initialize the settings of `syscall`
bors r+

Implement syscall

---

kernel/src/graphics/screen/layer.rs
kernel/src/lib.rs
kernel/src/mem/allocator/phys.rs

- refactor: use `try_into`
- chore: initialize desktop and log first
- fix: grammer
- refactor: remove a debug function
- fix: panic if a computer has lots of memory
bors r+

fix: kernel panic when a computer has lots of memory

---

kernel/src/device/pci/ahci/registers/generic.rs
kernel/src/device/pci/ahci/registers/port.rs
kernel/src/device/pci/xhci/structures/registers/capability.rs
kernel/src/device/pci/xhci/structures/registers/doorbell.rs
kernel/src/device/pci/xhci/structures/registers/operational.rs
kernel/src/device/pci/xhci/structures/registers/runtime.rs
kernel/src/device/pci/xhci/structures/registers/usb_legacy_support_capability.rs
kernel/src/interrupt/apic/io.rs
kernel/src/interrupt/apic/local.rs
kernel/src/interrupt/apic/pic.rs
kernel/src/interrupt/timer.rs
kernel/src/lib.rs
kernel/src/mem/accessor.rs
kernel/src/mem/allocator/acpi.rs
kernel/src/syscall.rs

- chore: separate `user` and `kernel` accessor
- Revert "chore: rewrite with `inb` and `outb`"
- fix: no timer interruptions happen
Fixes: #522 
bors r+

fix: no timer interruptions happen

---

kernel/src/device/pci/xhci/mod.rs
kernel/src/device/pci/xhci/port/mod.rs
kernel/src/device/pci/xhci/port/spawner.rs

- chore: create `spawner.rs`
- chore: define `Spawner` struct
- chore: define `Spawner::spawn`
- refactor: rename to `max_num`
- chore: rename to `try_spawn`
- chore: define `spawn` method
- chore: define `scan_all_ports_and_spawn`
- chore: make a struct and methods public
- fix: wrong port number was specified
- refactor: rewrite with `Spawner`
- refactor: rename to `sender`

refactor: define `Spawner`

---

kernel/src/device/pci/xhci/port/spawner.rs

- chore: define `SPAWN_STATUS`
- chore: define `add_task_for_port` method
- chore: define `mark_as_spawned`
- chore: mark a port as spawn
- chore: define `spawned` method
- chore: define `spawnable` function
- chore: rewrite the conditional expression with `spawnable`
After resetting, the Port Status Change TRB is issued. This commit prevents to create a new task for the port in response to the TRB.

chore: do not spawn a port task if a task for it is already spawned

---

kernel/src/device/pci/xhci/port/mod.rs
kernel/src/device/pci/xhci/port/spawner.rs

Not to create an instance of `Spawner` to spawn tasks.
bors r+

refactor: provide functions to spawn tasks

---

kernel/src/device/pci/xhci/mod.rs
kernel/src/device/pci/xhci/port/mod.rs
kernel/src/device/pci/xhci/port/spawner.rs
kernel/src/device/pci/xhci/structures/ring/event/mod.rs
kernel/src/device/pci/xhci/structures/ring/event/trb/mod.rs

- chore: add `PortStatusChange::port`
- refactor: rename to `spawn_all_connected_port_tasks`
- chore: define `try_spawn` function
- refactor: define `spawner` function
- fix: forgot to make `PortNotConnected` public
- chore: make `PortStatusChange::port` public
- chore: spawn a new task after receiving the Port Status Change TRB

chore: handle the Port Status Change TRB

---

.gitignore
kernel/Cargo.toml
kernel/src/device/pci/config/mod.rs
kernel/src/lib.rs
kernel/src/mem/accessor.rs
kernel/src/mem/allocator/page_box.rs
kernel/src/multitask/executor.rs
kernel/src/panic.rs
kernel/src/syscall.rs
syscalls/Cargo.toml
syscalls/src/lib.rs

- chore: add `syscalls` crate
- chore: ignore all `target` directory from tracking
- refactor: split `syscalls.rs`
bors r+

refactor: split `syscall.rs`

---

kernel/src/device/pci/xhci/port/mod.rs

chore: warn if a connected device is unrecognized

---

kernel/src/process/stack_frame.rs

The RFLAGS was created by reading the working one. Processes were created while the interruption was disabled. This is why the timer was not working correctly.
Fixes: #547 
bors r+

fix: no interruptions from timer

---

kernel/src/device/pci/xhci/structures/scratchpad.rs

fix: scratchpad was ill-aligned

---

kernel/src/device/pci/xhci/structures/descriptor.rs

- fix: wrong endpoint type was specified
- fix: the wrong formula was used to generate `EndpointType`
bors r+

fix: wrong endpoint type was generated

---

kernel/Cargo.toml

chore(deps): use `acpi` crate on crates.io

---

kernel/src/lib.rs
kernel/src/process/manager.rs
kernel/src/process/mod.rs
kernel/src/syscall.rs

- refactor: remove `getpid` from `process` module
- refactor: remove `process::add` function
- refactor: remove an unnecessary `(crate)`
- refactor: public functions should first
- refactor: public things should come first
- refactor: remove an unnecessary `pub`
- refactor: remove an unnecessary `pub`
bors r+

refactor: process module

---

kernel/src/device/pci/xhci/exchanger/command.rs
kernel/src/device/pci/xhci/exchanger/transfer.rs
kernel/src/device/pci/xhci/structures/ring/command/mod.rs
kernel/src/device/pci/xhci/structures/ring/command/trb.rs
kernel/src/device/pci/xhci/structures/ring/mod.rs
kernel/src/device/pci/xhci/structures/ring/transfer/mod.rs
kernel/src/device/pci/xhci/structures/ring/transfer/trb/control.rs
kernel/src/device/pci/xhci/structures/ring/transfer/trb/mod.rs

- refactor: apply the builder pattern for constructing the Command TRBs
- refactor: dereference instead of `clone`
- refactor: apply the builder pattern for constructing the Normal TRB
- refactor: apply the builder pattern for constructing the Contorl TRBs
- refactor: define `trbs_for_getting_descriptors`
bors r+

refactor: apply the builder pattern for constructing TRBs

---

kernel/src/device/pci/xhci/port/slot.rs

chore: suppress the unrecognized descriptor warning

---

kernel/src/device/pci/xhci/port/resetter.rs

chore: fix the license notation position

---

kernel/src/lib.rs
kernel/src/process/manager.rs
kernel/src/tests/process.rs

fix: avoid deadlocking by using `ArrayQueue`

---

kernel/src/process/collections/process.rs
kernel/src/process/exit.rs
kernel/src/process/mod.rs
kernel/src/process/page_table.rs
kernel/src/process/switch.rs

- chore: create page tables of each process in the process manager space
- refactor: change the order of members
- refactor: remove an unused function
Fixes: #630
bors r+

chore: create stack and stack frame of each process in the address space of the process manager

---

kernel/src/tests/mem.rs
kernel/src/tests/mod.rs
page_box/src/lib.rs

- refactor: remove an unnecessary method
- chore: implement `Clone` for `PageBox<T>`
- refactor: remove `Copy` trait bound
- chore: implement `Clone` for `PageBox<[T]>`
- test: add a test for cloning page boxes
bors r+

chore: implement `Clone` for `PageBox`

---

kernel/Cargo.toml
kernel/src/device/pci/xhci/port/mod.rs
kernel/src/device/pci/xhci/structures/context.rs
kernel/src/device/pci/xhci/structures/dcbaa.rs
kernel/src/device/pci/xhci/structures/registers/capability.rs
kernel/src/device/pci/xhci/structures/registers/operational.rs
kernel/src/device/pci/xhci/structures/registers/runtime.rs
kernel/src/device/pci/xhci/structures/ring/command/mod.rs
kernel/src/device/pci/xhci/structures/ring/event/mod.rs
kernel/src/device/pci/xhci/structures/scratchpad.rs
kernel/src/device/pci/xhci/xhc.rs

- chore: update the version of `xhci` to 0.2.0
- chore: rewrite with `xhci` crate
- chore: rewrite with `xhci` crate
- refactor: rewrite with `xhci` crate
- refactor: remove unused lines
- fix: method names
- chore: update the version of `xhci` crate
- refactor: rewrite with `xhci` crate
- chore: update the version of the `xhci` crate
bors r+

refactor: rewrite with `xhci` crate

---

kernel/src/device/pci/xhci/exchanger/transfer.rs
kernel/src/device/pci/xhci/mod.rs
kernel/src/device/pci/xhci/port/endpoint.rs
kernel/src/device/pci/xhci/port/mod.rs
kernel/src/device/pci/xhci/port/resetter.rs
kernel/src/device/pci/xhci/structures/context.rs
kernel/src/device/pci/xhci/structures/dcbaa.rs
kernel/src/device/pci/xhci/structures/extended_capabilities.rs
kernel/src/device/pci/xhci/structures/mod.rs
kernel/src/device/pci/xhci/structures/registers.rs
kernel/src/device/pci/xhci/structures/ring/command/mod.rs
kernel/src/device/pci/xhci/structures/ring/event/mod.rs
kernel/src/device/pci/xhci/structures/scratchpad.rs
kernel/src/device/pci/xhci/xhc.rs

- chore: add `registers.rs`
- chore: move codes to the `register` module
bors r+

refactor: create `registers` and `extended_capabilities` modules

---

rustfmt.toml

chore: replace `merge_imports` with `imports_granularity`

---

kernel/src/interrupt/handler.rs
kernel/src/interrupt/idt.rs

Stopping QEMU by the unhandled interrupts is easier to debug.
bors r+

chore: remove the unused interrupt handlers

---

common/src/constant.rs
kernel/src/device/keyboard.rs
kernel/src/device/mouse.rs
kernel/src/interrupt/handler.rs
syscalls/src/lib.rs

I can't figure out why the keyboard driver and the mouse driver could
access without the system calls.
bors r+

chore: use system calls to access the I/O ports

---

bootx64/src/fs/mod.rs

- refactor: shorten the variable names
- refactor: use a safe way to generate the `RegularFile`
bors r+

refactor: use the safe way to convert a file handler

---

kernel/src/lib.rs

Eventually calling a system call will be to send a message. This needs
processes to exist, but before creating them system calls cannot be
called. Ultimately this function should be removed.
bors r+

chore: minimize the size of the `initialize_in_user_mode` function

---

kernel/src/interrupt/idt.rs
kernel/src/lib.rs
kernel/src/process/mod.rs
kernel/src/process/switch.rs

Eventually, interrupts will be handled by the common mechanism.
bors r+

chore: use the privilege stack table, instead of the interrupt one

---

kernel/src/lib.rs
kernel/src/multitask/executor.rs
kernel/src/multitask/task.rs
kernel/src/panic.rs
kernel/src/syscall.rs
syscalls/src/lib.rs

The user process should not modify interrupt settings. For example, if
the timer interrupts are disabled, process switch will no longer happen.
bors r+

chore: remove the system calls which handle interrupts

---

kernel/src/syscall.rs

When a system call is called, interrupts are automatically disabled.
bors r+

refactor: remove `cli` and `sti` for `syscall`

---

kernel/src/interrupt/handler.rs
kernel/src/interrupt/idt.rs
kernel/src/lib.rs
kernel/src/process/collections/process.rs
kernel/src/process/mod.rs
kernel/src/process/stack_frame.rs
kernel/src/syscall.rs
syscalls/src/lib.rs

This makes it easier to save registers because the `RSP` is changed on
interrupt.
bors r+

chore: use interrupts to call system calls

---

kernel/src/tests/process.rs

500 is enough. Every process including the test processes will be
switched 4 or 5 times.
bors r+

test: halve the count goal

---

kernel/src/interrupt/idt.rs
kernel/src/process/mod.rs
kernel/src/process/switch.rs
kernel/src/tss.rs

`RSP` will not be set to the right position of the stack frame if the
privilege stack table is used and an interrupt happens during the
kernel privilege process.
bors r+

chore: use the interrupt stack table

---

kernel/src/device/pci/xhci/port/class_driver/mass_storage/mod.rs

The ideal is to remove the code which writes to the device, but for the
future use, I have decided not to remove it.
bors r+

chore: write to the USB mass storage device after reading it

---

kernel/src/device/pci/xhci/port/class_driver/mass_storage/mod.rs
kernel/src/device/pci/xhci/port/class_driver/mass_storage/scsi/command_data_block.rs
kernel/src/device/pci/xhci/port/class_driver/mass_storage/scsi/mod.rs

- chore: add the `command_data_block` module
- refactor: move the definitions of CDB to the proper module
bors r+

refactor: move the definitions of CDB to the proper module

---

kernel/src/device/pci/mod.rs
kernel/src/device/pci/xhci/exchanger/command.rs
kernel/src/device/pci/xhci/mod.rs
kernel/src/device/pci/xhci/xhc.rs

- refactor: limit the visibility of a function
- refactor: rename to `iter_xhc`
- refactor: No-op command is no longer issued
- refactor: define the `spawn_tasks` function
- fix: wrong iteration of the PCI devices
- refactor: define `xhc::exists` function
- refactor: define `init_and_spawn_tasks`
- refactor: remove the unused struct
- refactor: remove the unused functions
- refactor: add a blank line
bors r+

refactor: xhci task

---

kernel/src/device/pci/xhci/mod.rs
kernel/src/device/pci/xhci/structures/extended_capabilities.rs
kernel/src/device/pci/xhci/structures/registers.rs

The safeties depend on an argument.
bors r+

chore: mark `init` functions as unsafe

---

kernel/src/device/pci/xhci/port/class_driver/mass_storage/mod.rs

chore: don't print the content of the USB mass storage device

---

kernel/src/process/collections/process.rs
kernel/src/process/collections/woken_pid.rs
kernel/src/process/ipc.rs
kernel/src/process/mod.rs

This ID will be used by the kernel, file server, and process manager to
sync the process information.
bors r+

refactor: rename `process::Id` to `SlotId`

---

Makefile

It is difficult to trace changes of files of source codes because these
crates depend on other crates in the ramen directory, and these
dependencies are often forgotten to write in the Makefile. Cargo exits
immediately if no changes occurred in the source codes. This commit
almost does not affect the building time.

refactor: depend on cargo to build the kernel library and bootx64.efi

---

run_qemu.sh

fix: do not use `bootx64.efi` as the image of USB storage

---

kernel/src/mem/allocator/phys.rs

- refactor: remove a parameter whose type is boolean
- refactor: rename `init_static` to `init`
- refactor: add the `new` suffix
- refactor: define a method to ask whether an area is available
- refactor: move lines in an if statement to a new method
- refactor: move lines in a if statement to a new method
- refactor: return immediately if a condition is not met
- refactor: use the guard return
- refactor: define `split_node_into_half` method
- refactor: define the `alloc_from_descriptor_index` method
bors r+

refactor: physical pages allocator

---

run_qemu.sh

To add crate-specific tests.
bors r+

test: run `cargo test` for each crate

---

bootx64/Cargo.toml
run_qemu.sh

- chore: disable tests for the crate `bootx64`
- refactor: `bootx64` crate is no longer excluded from testing
bors r+

refactor: disable tests for the crate `bootx64`

---

kernel/src/mem/allocator/phys.rs

- refactor: use `Vec`
- refactor: remove the `Lazy` wrapper
bors r+

refactor: use `Vec` instead of `VecDeque`

---

frame_manager/Cargo.toml
frame_manager/src/lib.rs
kernel/Cargo.toml
kernel/src/mem/allocator/phys.rs

To test the frame manager. It is not possible to do tests in the
`kernel` crate because custom targets do not have their own `std`
crates.
bors r+

refactor: create the `frame_manager` crate

---

frame_manager/src/lib.rs

The previous implementation used the buddy-like algorithm. However, it was not complete. This PR removes the buddy-like algorithm and instead use the flat list algorithm. It is simple and easy to test.

chore: remove the buddy-like altorithm from the frame manager

---

Makefile

chore: use the portable ascii format of the cpio file

---

kernel/src/syscall.rs

chore: remove the `no_mangle` attribute

---

kernel/src/device/pci/xhci/structures/ring/event/segment_table.rs

refactor: use `into` instead of `from`

---

kernel/src/process/page_table.rs

fix: panic when mappings are overlapped

---

kernel/src/fs.rs

To calculate the address of the start of content.
bors r+

refactor: define `name_start`

---

kernel/src/process/mod.rs
kernel/src/process/stack_frame.rs

To load a ELF file. Converting an `usize` value to a function pointer
needs `transmute`.
bors r+

chore: store the entry address of a function, not the pointer

---

kernel/src/process/page_table.rs

refactor: use tuple matching to reduce the number of lines

---

bors.toml

Bors can do a squash merge, but it will mark a PR as closed, not merged.

ci: we no longer use Bors

---

Makefile
kernel/Cargo.toml
kernel/src/lib.rs
port_server/.cargo/config.toml
port_server/Cargo.toml
port_server/src/lib.rs
port_server/x86_64-unknown-ramen.json

Currently, the process manager panics because it cannot get a lock of `HEAP`. This must be resolved.

chore: create the port server binary

---

ralib/src/mem/mod.rs

Reverts toku-sa-n/ramen#937
It turned out that adding the `heap` feature is useless. `_print` still uses the `String` type.

Revert "fix(ralib): forgot to add `cfg`"

---

ralib/Cargo.toml
ralib/src/lib.rs

Reverts toku-sa-n/ramen#939
Memory managers can use their own heap systems rather than the ones provided by `ralib`.

Revert "chore(ralib): remove the `heap` feature"

---

Makefile

This commit defines the `cargo_project` function, which returns all files of a project managed by cargo.

refactor(Makefile): define a function

---

kernel/src/asm.s
kernel/src/lib.rs
kernel/src/process/exit.rs
kernel/src/process/mod.rs
kernel/src/syscall.rs

Using external assembly makes it difficult to debug code.

refactor(kernel): inline external assemblies

---

kernel/src/process/collections/woken_pid.rs
kernel/src/process/mod.rs

I noticed that in the woken_pid.rs the add and push functions have the same functionality so I removed one to clear up the redundancy

removal of redundant woken_pid function

---

libs/raheap/Cargo.toml
libs/raheap/src/lib.rs
libs/ralib/Cargo.toml
libs/ralib/src/lib.rs
libs/ralib/src/mem/mod.rs
servers/do_nothing/Cargo.toml
servers/do_nothing/src/lib.rs
servers/fs/Cargo.toml
servers/fs/src/lib.rs
servers/pm/Cargo.toml
servers/pm/src/lib.rs
servers/port_server/Cargo.toml
servers/port_server/src/lib.rs
servers/xhci/Cargo.toml
servers/xhci/src/lib.rs

This commit splits the `ralib` crate and moves its heap implementation to the newly created `raheap` crate to prevent the duplicated global heap error caused by the workspace property.

chore: create the `raheap` crate

---

bootx64/Cargo.toml
bootx64/src/fs/mod.rs
bootx64/src/jump.rs
bootx64/src/mem/paging.rs
bootx64/src/mem/stack.rs
kernel/Cargo.toml
kernel/src/mem/allocator/virt.rs
kernel/src/mem/paging/mod.rs
kernel/src/mem/paging/pml4.rs
kernel/src/process/mod.rs
kernel/src/tss.rs
libs/common/Cargo.toml
libs/common/src/kernelboot.rs
libs/common/src/lib.rs
libs/common/src/mem/reserved.rs
libs/predefined_mmap/Cargo.toml
libs/predefined_mmap/src/lib.rs
libs/terminal/Cargo.toml
libs/terminal/src/vram.rs

This commit moves the `constant` module in the `common` crate to the newly created `predefined_mmap` crate. The name "common" originates from "things which both the kernel and the bootloader codes need". However, the term is ambiguous, and I threw lots of codes into the crate. So this commit splits the `common` crate.

refactor: create the `predefined_mmap` crate

---

bootx64/Cargo.toml
bootx64/src/exit.rs
bootx64/src/gop.rs
bootx64/src/jump.rs
bootx64/src/main.rs
bootx64/src/mem/paging.rs
kernel/Cargo.toml
kernel/src/lib.rs
libs/boot_info/Cargo.toml
libs/boot_info/src/lib.rs
libs/boot_info/src/mem.rs
libs/boot_info/src/vram.rs
libs/common/Cargo.toml
libs/common/src/lib.rs
libs/common/src/mem/mod.rs
libs/common/src/mem/reserved.rs
libs/terminal/Cargo.toml
libs/terminal/src/vram.rs

This commit moves the `kernelboot` module to the newly created `boot_info` crate. There are two purposes to do this. Firstly, to remove the `common` crate, which is now a garbage can where codes have nowhere to go. Secondly, to solve a problem caused by the workspace's property. Currently, the `boot_info` crate depends on the `uefi` crate, so does the `bootx64` crate. Also, the `bootx64` crate enables its allocation feature.
Furthermore, the kernel depends on the crate so that the compiler will build the kernel with the duplicated global allocator. See https://stackoverflow.com/questions/68955652/how-to-avoid-global-allocator-conflicts/68977928#68977928 for the detail. On another PR, I will remove the `uefi` dependency from the crate.

refactor: create the `boot_info` crate

---

libs/predefined_mmap/Cargo.toml
libs/raheap/Cargo.toml
servers/pm/Cargo.toml

Dependabot does not work well with edition 2021.

chore: use edition 2018

---

Makefile
bootx64/src/main.rs
kernel/build.rs
kernel/src/fs.rs
kernel/src/initrd.s
libs/common/src/mem/reserved.rs

chore: separate the initrd binary from the kernel

---

kernel/src/gdt.rs
kernel/src/lib.rs

It dereferences a raw pointer.

fix: `gdt::init` is an unsafe function

---

kernel/src/process/scheduler.rs

Clippy will complain about `lock_scheduler` for the name repetition.

refactor: `s/lock_manager/lock`

---

kernel/src/lib.rs
kernel/src/tests/process/mod.rs

We will remove the exit system call. It turned out that it is difficult
to implement it correctly.

test: remove the exit test

---

.github/workflows/test.yml

I think this solves the problem that Clippy always fails on the first
run for PRs from the others.

ci: do not run on push
